### ISSUE TITLE
false positive - iMessage 

### ISSUE THREAD

**Issue by bigalownz** [CIDRAM/CIDRAM#263] opened 2021-10-05 06:22 UTC
Please use this template when reporting bugs, problems, issues, etc.

## Server information.
ubuntu 20.04

### CIDRAM version used (if known, please also include the exact commit hash).
CIDRAM v2.7.0

### PHP version installed 
7.4.24

---
## Issue
false positive

Signatures Reference

functions.php:L1094 »
Why Blocked
Fake Facebook external hit!
User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0 »

having a lot of these over the last week and it
turns out this is  iMessage

**Comment by 737simpilot** [comment] 2021-10-05 07:11
So what's the IP address? At least the first three octets... 192.168.1.xxx

**Comment by Maikuolan** [comment] 2021-10-11 03:30
It seems, in this case, we don't really need the IP address, because the problem is caused by iMessage's choice of user agent.

*Excerpt source: https://medium.com/@siggi/apples-imessage-impersonates-twitter-facebook-bots-when-scraping-cef85b2cbb7d*
*Written/Authored by Siggi Simonarson (@siggisim).*
> There are a few interesting things about the User Agent header that iMessage uses, but the most glaring is that **iMessage is pretending to be both Twitter’s [Twitterbot](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#url-crawling-and-caching) and Facebook’s [Facebot](https://developers.facebook.com/docs/sharing/webmasters/crawler).**
>
> I stumbled upon this while building [Hyperlink](http://usehyperlink.com/), an iPhone app that allows you generate links that send you a push notification when they’re clicked on. I noticed that when you sent a Hyperlink via iMessage, you immediately received a push notification. I was doing some user agent detection to label clicks that came from bots, but noticed that links sent via iMessage were appearing as scraped by Facebook or Twitter bot.
>
> The second interesting thing about this user agent is that while this request is made directly from the sending iPhone, not an Apple server somewhere — it claims to come from a Desktop Mac (*Macintosh; Intel Mac OS X 10_11_1*) rather than an iPhone (iPhone user-agent strings typically begin with *Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X)*.
>
> My best guess for why Apple decided to spoof these two popular services and pretend to be a desktop when making its requests is that some sites may use custom logic for rich previews shown on Facebook and Twitter. Microsoft Edge does [something similar](https://superuser.com/questions/1174028/microsoft-edge-user-agent-string) in sending up Mozilla, Safari, and Chrome in its user agent header, but at least it includes *Edge/14* at the end of its string so it’s possible to tell where the request is really coming from.
>
> This may seem not seem so bad on the surface, but spoofing user agents makes it difficult to get an accurate picture of where your web traffic is coming from. It also breaks standards like [robots.txt](https://developers.google.com/search/reference/robots_txt) (which iMessage doesn’t seem to respect either) which allow you to control how crawlers crawl your site. It’s bad behavior that you might expect from a scrappy startup or a malicious crawler — not the [second largest company](https://en.wikipedia.org/wiki/List_of_public_corporations_by_market_capitalization) in the world.

Because CIDRAM attempts to verify the authenticity of requests from both Facebook and Twitter alike, and blocks those such requests which are "fake" (i.e., claiming, falsely, to be from Facebook/Twitter), and because iMessage is claiming to be from *both* of them (and is actually from neither), CIDRAM is blocking iMessage requests accordingly.

If only iMessage actually included some kind of unique identifier within its user agent (something like *iMessage vX.Y.Z* would be ideal, but anything/whatever would do just fine, as long as it's unique to iMessage), I could probably use *that* to write some kind of bypass, or adjust CIDRAM's own expressions for identifying Facebook/Twitter requests accordingly, in order to have CIDRAM's verification process ignore iMessage requests. Unfortunately though, it *doesn't* seem to include any such kind of unique identifier.

Not quite sure offhandedly what I can do to fix this problem. I'll need to think on it for a while, I reckon. Forewarning though: I *suspect* that this might end up becoming a "wontfix" and being added to CIDRAM's list of incompatible services/platforms/etc.

**Comment by 737simpilot** [comment] 2021-10-21 01:46
So it can't be pinned to an IP, CIDR or ASN/s?

Reminds me of Mozilla's craptacular way of verifying HSTS pre-load. Their ASN is one that I block at the Cloudflare level for obvious reasons. May be Azure. Can't remember offhandedly. But, their choice of UA is crap and thus hard to whitelist based on an IP to UA ratio. I don't even think a PTR lookup would work for verification of the the HSTS pre-load bots either.

**Comment by Maikuolan** [comment] 2021-10-21 02:16
> So it can't be pinned to an IP, CIDR or ASN/s?

Yep. Because the requests are coming from the client's device (their phone), they'll be seen as coming from whichever network the client's device is connected to (in other words, these requests could, in theory, come from almost anywhere).

**Comment by bigalownz** [comment] 2021-12-20 07:46
any word on a fix for this yet ??
thanks

**Comment by bigalownz** [comment] 2022-02-17 11:48
bump for a fix

**Comment by Maikuolan** [comment] 2022-02-17 17:22
I have some ideas about possible ways to fix this, but haven't tested those ideas out yet.

I'll do some testing tomorrow afternoon and reply with the results. :-)

**Comment by Maikuolan** [comment] 2022-02-18 14:08
The false positive should now be fixed as of the latest update. :-)

I'd initially hoped to be able to implement some kind of control mechanism, configuration directive, or such to allow users to *choose* whether or not they'd like to make any concessions to iMessage (because despite being an actual legitimate phone messaging app, iMessage still *is*, after all, masquerading as both Facebot and Twitterbot, and *both at the same time*, no less, so there's a good chance that *some* users will still be wanting CIDRAM to block it, although most users should be wanting it to *not* be blocked, given that blocking it affects iMessage), but after experimenting with various ideas at my end for a while now, it seems to me to be a little too complicated and difficult to really properly accomplish that than I'd like, so I don't think I'll bother trying to implement such a control mechanism or configuration directive for it anymore (at least, not for this major version, but I plan to completely rework how verification works in CIDRAM for v3, so we'll see what happens at that time, I guess).

However, as for such concessions themselves.. that's been reasonably easy to implement. Basically, what's happening now is that CIDRAM will look for the respective user agent partials for Facebot and Twitter in order to determine whether verification needs to occur (so far, this is what we were already doing), but will *also* now check whether those partials are present *together* (as per the specific pattern used by iMessage's user agent), or *in isolation*. If they're together, no verification occurs (thus allowing iMessage to have access). If they're in isolation, verification occurs as per usual. :-)

Anyway, should all be good now. The only shortfall is that the changes applied for iMessage aren't configurable (beyond the existing wider configurability of verification as a whole).

**Comment by 737simpilot** [comment] 2022-02-19 10:13
In an effort to complicate things even more... LOL I'm starting to believe more and more as time goes on with my use of CIDRAM and having a web presence, that it _might_ seem prudent to analyze certain requests based on their "signature/fingerprint."

What I mean by that is the combinations of metrics like IP, UA, PTR, headers, request method request type, HTTP version, etc. So in this instance for iMessage we know that it's generated via a phone. Thus we have two MAJOR IP/ISP metrics to go on. 1) It's most probable this iMessage UA will come from a legit ISP and 2) Or possibly a mobile carrier.  (leaving out the use of VPNs or proxies as those are most likely blocked with CIDRAM anyway).

So, based on that that metric example above with the IP/ISP and in combination with this very unique UA, we now have a more reliable "fingerprint/signature me thinks." Of course, we might be able to combine that fingerprint/signature with other things I pointed out like a PTR, headers, HTTP version, etc to _help_ further "tune" the fingerprint/signature match for positive verification while trying to weed out malicious intent using this UA for masquerading purposes.  

I don't know, just kinda thinking out loud here, and as I mentioned, I've been of the belief a type of fingerprint/signature type thing might be prudent. I did say it complicates things. LOL Of course, something of this nature needs to be based on a lot of research and statistics. For me that's kinda how I've been doing things in Cloudflare and it's been baby steps and years worth of observation. I have many, many specific tuned firewall rules because of me learning things about connections. I've already maxed out the allotted 256 rules I think it is. LOL It's been damn effective though. They're either blocked due to the whole country blocks or my specific rules in Cloudflare, while CIDRAM picks up the slack in a dual layer approach. And there are things CIDRAM does Cloudflare doesn't and vice versa. While also making sure legit traffic isn't caught up. And so far that's seldom ever the case. 

I guess what I just described is heuristics. Like what is used in anti-virus software. And now that I think of it, I'm sure professional firewalls that utilize IDS mechanisms use a form of heuristics. I know pfSense uses Snort and that could be like a heuristics thing. 

The chief difference with anti-virus software and a firewall however is the type of data filtering being used for lack of the correct term. They're like two different types of data in the OSI layer. Where anti-virus software is layer 7, and firewalls/IDS is ALL OSI layers. Well, maybe not layer 1 in the context a firewall/IDS doesn't protect against ingress/egress, RFI, spurious emissions, etc. That's more within the realm of something called [TEMPEST](https://en.wikipedia.org/wiki/Tempest_(codename))

Anyway...



![img](https://i.imgur.com/a6hktAF.gif)

**Comment by Maikuolan** [comment] 2022-02-21 14:15
I've started working on v3 now, so.. we'll see what happens. '^.^

But anyway, seeing as this issue has been solved now, I'll go ahead and close it.

**Closed as completed by Maikuolan** 2022-02-21 14:15 UTC
Labels: Won't Fix, False Positive

**Comment by bigalownz** [comment] 2023-03-08 07:54
still getting false positives with cidram 3

**Comment by Maikuolan** [comment] 2023-03-17 16:46
Changing labels at this issue from `Fixed` to `Won't Fix` due to new complications discovered which affect Twitterbot verification.
