### ISSUE TITLE
Sitemap error

### ISSUE THREAD

**Issue by alamrekane1** [CIDRAM/CIDRAM#166] opened 2020-01-17 11:43 UTC
When signatures➡block_generic are enabled, a Webmaster Tools error occurs in the Sitemap

**Comment by Maikuolan** [comment] 2020-01-17 12:11
Investigating now. :+1:

**Comment by alamrekane1** [comment] 2020-01-17 12:19
> Investigating now. 👍

Thanks for the quick response pending solution
The plugin used to create Sitemap Rank Math SEO

**Comment by Maikuolan** [comment] 2020-01-17 12:43
Thanks for the information, and thanks for reporting the problem. :-)

Any log information available (e.g., from CIDRAM logs, website access logs, etc)? Having a little difficulty replicating the problem at my side (maybe they connected from different IPs, but I'm not sure). Log information can help to determine exactly which signatures are responsible for the problem. :-)

(If not available, no worries; I will keep investigating regardless, but may just take a little longer).

**Comment by alamrekane1** [comment] 2020-01-17 12:56
These are the records of the days 13, 14, 15, 16
https://www.mediafire.com/file/27lszzde7m2te44/logfile.zip

**Comment by alamrekane1** [comment] 2020-01-18 13:32
is there a solution

**Comment by Maikuolan** [comment] 2020-01-19 03:38
Sorry for the delay; Past few days have been a little busy. Thanks for your patience. :-)

So, looking at the attached records, it seems that Sitemap Rank Math SEO doesn't have a distinct user agent of its own (I searched for permutations of the plugin's name, e.g. "sitemap", "rank", "math", "seo", "webmaster tools", etc, and for any unusual, unfamiliar user agents I could find in the logs, etc, but couldn't see anything in there seemingly related to the plugin). Because of that, I had to look through all the attached records a little more carefully, to try to determine exactly which records might've been related to the plugin (this is important, because knowing exactly which records are related, tells us which records we should be looking at in order to know exactly which signatures are causing the problem).

Because (as you initially mentioned) the problem occurs when signatures➡block_generic is enabled, we can use some process of elimination to know which records are *not* related (i.e., related records should have "Generic" marked in the "Why Blocked" field; so, records marked instead with other things, e.g., "Cloud service", can be ignored at the moment). Also, because the problem affects sitemaps, any records not related to sitemaps can be ignored at the moment, too. So, I should be looking for records marked as "Generic", which also have a referrer or reconstructed URL indicating the record is related to sitemaps. Before this process of elimination, we have a total of 34,545 records; after this process of elimination, we're left with just 34 records (a much smaller, much easier number to work with).

*Calculated by performing a regular expression match against all the records:*
```regex
(Why Blocked\: Generic[^\n]+\n([^\n]+\n)*[^\n]+sitemap|sitemap[^\n]+\n([^\n]+\n)*[^\n]+Why Blocked\: Generic)
```

And, without exception, all 34 of these records were caused by the "Hetzner Online GmbH" signatures. Also without exception, they all cite a standard WordPress user agent (i.e., like `WordPress/x.x.x; zzz`, where `x.x.x` is the currently installed WordPress version, and `zzz` is the URL of the website or domain where installed), which I know from past experience, is a user agent that many different WordPress plugins tend to use (so, would suggest that these records were most likely also caused by a plugin). So currently, my suspicion is that those particular signatures are the signatures responsible for the problem.

Assuming that my suspicion is correct, instructing CIDRAM to ignore the "Hetzner Online GmbH" signatures should solve the problem, and would probably be the easiest and simplest way to solve the problem.

This can be done from the front-end via the "Sections List" page.
![1](https://user-images.githubusercontent.com/12571108/72674221-34ef3080-3aaf-11ea-9992-a0749f4b9197.png)

After loading the "Sections List" page, you can search for "Hetzner Online GmbH" and click the connected "Ignore this" link.
![2](https://user-images.githubusercontent.com/12571108/72674222-34ef3080-3aaf-11ea-9df2-29d97b75b639.png)

After clicking the link, the section should become greyed out, as per shown in the image.
![3](https://user-images.githubusercontent.com/12571108/72674223-34ef3080-3aaf-11ea-9dfe-d74e49260510.png)

Alternatively, if not using the front-end, the `ignore.dat` file can be manually edited in order to instruct CIDRAM to ignore the signatures, too. Instructions for how to manually edit the file are included within the file itself.

Of course, the only way to 100% confirm my suspicion would be to test it. If you try this solution, after doing so, I would recommend to test the Sitemap plugin again, to check whether the problem persists. If possible, also let me know whether the solution works (if it doesn't work, it would mean that my suspicion might've been wrong, and I'll need to investigate other possible solutions). Cheers. :-)

**Comment by alamrekane1** [comment] 2020-01-19 18:38
Thank you "**Maikuolan**" the problem has already been solved
I found out that my server, which is hosted by **Hetzner**, is being blocked. Can the ban be lifted by **cidram**?

**Comment by DanielRuf** [comment] 2020-01-21 09:19
Hm, you would have to create a bypass / whitelist it as this is not a normal ISP but hosting provider that CIDRAM blocks for good reasons.

**Comment by Maikuolan** [comment] 2020-01-22 08:17
> Can the ban be lifted by **cidram**?

At the upstream (i.e., here), I would prefer not to, because like Daniel already mentioned;

>  this is not a normal ISP but hosting provider that CIDRAM blocks for good reasons.

In particular, a long history of spam campaigns originating from that network, hack attempts and all kinds of other unwanted traffic over the course of many, many years.

However, you can lift it *in effect*, either by instruction CIDRAM to ignore it (per my earlier advice), or (per Daniel's earlier advice) by bypassing/whitelisting/greylisting it. You can whitelist or greylist it via your custom signatures file, or bypass it by creating a custom module (if you're prefer to try that approach). Instructions are readily available for either approach. :-)

If the previously mentioned mechanisms aren't desirable, or aren't viable for some reason, CIDRAM's "auxiliary rules" feature is another mechanism capable of achieving the same thing, so you could try that too, but the previously mentioned mechanisms should already be sufficient in this case, so I don't think that writing any auxiliary rules would be necessary.

If you'd like to literally remove the signatures from your signature files entirely, you can do that too, but I'd recommend against that, because any changes made to the default signatures files would be lost the moment you update those files (due to those changes not existing at the upstream). Using the `ignore.dat` file, or using the custom signatures file (which shouldn't normally be updated from the upstream anyway), or writing custom modules (whenever the previously mentioned approaches aren't viable for some reason) would be the better approach.

**Comment by alamrekane1** [comment] 2020-01-22 17:03
I followed the previous instructions:
Bypass has already been used by "auxiliary rules" to exclude ip server.
Thank you, happy for your cooperation
@Maikuolan 
@DanielRuf

**Comment by Maikuolan** [comment] 2020-01-23 02:26
Happy to help. :-)

**Closed as completed** 2020-01-23 02:26 UTC
Labels: Resolved, Support
