### ISSUE TITLE
PDO not working

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#158] opened 2019-12-26 11:44 UTC
just to keep a record that PDO is apparently not working

**Comment by DanielRuf** [comment] 2019-12-26 12:02
Hi, please specify what you mean with "not working" and provide the steps that you have done.

**Comment by mikeruss1** [comment] 2019-12-26 12:13
We have been discussing this for months and there have been several attempts to fix it. essentially no data is recorded on the DBs.

**Comment by Maikuolan** [comment] 2019-12-27 04:34
Working on this now. I'll reply a little later today.

**Comment by Maikuolan** [comment] 2019-12-27 06:46
Found the problem. Working on a fix now.

**Comment by Maikuolan** [comment] 2019-12-27 08:05
Got it working properly at my local dev system now, for everything except when checking updates page (I suspect most likely due to a bottleneck somewhere; not confirmed yet). Working on that now.

**Comment by Maikuolan** [comment] 2019-12-27 09:52
Hmm.. Turned off PDO entirely, and yet the new issue at the updates page remains.. ¬.¬

Might be that something has gone wrong at my local dev system unrelated to PDO. If so, then at least, that means I've got PDO now 100% working properly at my local dev system. But, I need to sort out whatever's gone wrong before I push any more commits.

Back to tinkering around and will report back here later.

**Comment by mikeruss1** [comment] 2019-12-27 11:19
that is good news, looking forward to testing version

**Comment by Maikuolan** [comment] 2019-12-27 15:02
Well.. No idea what was going on at my local dev system before, but everything seems to be working fine again now, without having changed anything (network issue maybe? no idea), so I've gone ahead and pushed the fix (https://github.com/CIDRAM/CIDRAM/commit/76f3183c5f03bdbe19378f48c560fdff6ccd2e88#diff-9afc10339e0b30d2858a66198b375bfb). I'll see about working towards doing some more refactoring in near future to try to alleviate possible bottlenecks or whatever else might've been slowing down the updates page before, but that's something for another issue anyway. At least, the particular issue at hand should be resolved now, so I'll go ahead and mark this as fixed. :-)

**Comment by mikeruss1** [comment] 2019-12-27 17:12
I have entries in the table!!

**Comment by mikeruss1** [comment] 2019-12-27 17:38
progress but issues.
the signature count is stuck on 1, the stats start date is empty, and no blocks recorded in stats
the cache contains ...
PDO – (Clear all)

Tracking – (Delete)
DNS-Forwards – (Delete)
DNS-Reverses – (Delete)
cidram-ver.yaml – (Delete)
php-ver.yaml – (Delete)

**Comment by mikeruss1** [comment] 2019-12-27 17:43
and no log file for today

**Comment by Maikuolan** [comment] 2019-12-28 00:59
Just to double-check and make sure: I assume that the "statistics" directive in the configuration is enabled?

**Comment by mikeruss1** [comment] 2019-12-28 08:17
oops, sorry about that.
I think its working, will give it some more tests later, but everything is OK with a couple of test blocks.
thank you !

**Comment by Maikuolan** [comment] 2019-12-28 09:02
Sounds good, and no worries. :+1: :-)

I'll close the issue as being now fixed for the moment. We can reopen it if we discover anything not yet fixed relating to this.

**Closed as completed by Maikuolan** 2019-12-28 09:02 UTC
Labels: Bug, Fixed

**Comment by mikeruss1** [comment] 2019-12-29 06:38
busy day yesterday!
the tracking data entry is empty - a:0:{}
the block worked fine and is in the log, but the tracking page shows nothing
the IP address is 127.0.0.1 and the hostname is localhost
apologies in advance if this is another config issue.

**Comment by Maikuolan** [comment] 2019-12-29 07:35
> apologies in advance if this is another config issue.

No problem at all. It *could* be, because there *is* a configuration directive ([track_mode](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#track_mode)) that affects how tracking works, but we won't know unless we check the configuration (so, it could be something else, too). Mind checking whether it's currently set to true or false? Cheers. :-)

**Comment by mikeruss1** [comment] 2019-12-29 07:54
ho hum, I think you know the answer !
I have checked valid entries and blocks. Stats is OK, tracking is OK.
DB has the following 10 rows, 
"Tracking"	a:1:{s:9:"127.0.0.1";a:2:{s:5:"Count";i:1;s:4:"Time";i:1578210767;}}
"DNS-Forwards"	"a:0:{}"	"0"
"DNS-Reverses"	"a:0:{}"	"0"
"cidram-ver.yaml"	"-"	"1577554161"
"php-ver.yaml"	"-"	"1577554161"
"Statistics"	"a:8:{s:11:""Other-Since"";i:1577520664;s:12:""Blocked-IPv4"";i:9;s:12:""Blocked-IPv6"";i:0;s:13:""Blocked-Other"";i:0;s:11:""Banned-IPv4"";i:0;s:11:""Banned-IPv6"";i:0;s:16:""reCAPTCHA-Failed"";i:0;s:16:""reCAPTCHA-Passed"";i:0;}"	"0"
"https://bitbucket.org/macmathan/blocklists/raw/master/cidramblocklists.dat"	"-"	"1577604666"
"https://raw.githubusercontent.com/CIDRAM/CIDRAM/v1/vault/components.dat"	"-"	"1577604666"
"https://raw.githubusercontent.com/CIDRAM/CIDRAM-Extras/master/modules/modules.dat"	"-"	"1577604666"
"https://raw.githubusercontent.com/CIDRAM/CIDRAM-Extras/master/themes/themes.dat"	"-"	"1577604666"

is there anything else I should test before putting it into production?

**Comment by Maikuolan** [comment] 2019-12-29 09:38
> is there anything else I should test before putting it into production?

LGTM. :+1:

**Comment by mikeruss1** [comment] 2019-12-29 10:07
Implemented and working

fingers crossed it fixes Stats clearing

many thanks
