### ISSUE TITLE
Reinstate IP Tracking status ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#120] opened 2019-05-31 15:09 UTC
In the event of the IP Tracking information being lost, is it possible to reinstate from a backup ?

**Comment by Maikuolan** [comment] 2019-06-01 08:26
With a bit of messing around, technically yes, it's possible. Might be easier to just let IP tracking repopulate itself naturally though.

The IP tracking information is stored in CIDRAM's cache data, alongside all the other cache data, so, manually copy/pasting IP tracking information from the backup, into the cache data, would restore it. But, copy/pasting it incorrectly could also corrupt the cache data, causing the whole lot to reset. Not impossible to do it correctly, of course, but given that the nature of cache data, is that it should be inherently temporary anyway, it's something I wouldn't usually worry about too much.

Alternatively, if there are some specific IPs that we don't want to write signatures for, but that we definitely know we want to block for while, if the IP tracking information for those IPs is accidentally deleted, we could always temporarily write some auxiliary rules to block those specific IPs, and then just delete those auxiliary rules a little later, when we feel that we don't need to block them anymore.

**Comment by mikeruss1** [comment] 2019-06-01 10:42
the issue is when it happens like it did yesterday, I loose all my banned entries, and within 30 mins I was being hit with hundreds of GETS, and as instaban doesnt seem to be working either, its somewhat annoying. There are hundreds of banned entries so not possible to use auxiliary rules.

I was just hoping there might be an easy way, if there isnt then as you say it will repopulate soon enough.

**Comment by Maikuolan** [comment] 2019-06-04 04:53
Understandable. TBH though, I don't think reinstating from a backup is necessarily an ideal solution anyway. The fact that everything is disappearing in the first place though, definitely isn't expected behaviour, and could indicate a problem somewhere.

Just thinking back a little on some strange behaviour that another user had reported experiencing a while back, thinking whether there could be some connection there.. Have you enabled any of the "supplementary cache options", by any chance? And if so, which ones?

**Comment by mikeruss1** [comment] 2019-06-04 16:02
Am away for a week so can't check. I don't remember setting it. Where is it in the config 

⁣Regards.... Mike
World War 2 Cruiser Operations

**Comment by Maikuolan** [comment] 2019-06-05 03:29
No problem at all. There's no rush, so enjoy your week away, and take your time. :-)

It should be right down, towards the very end of the configuration. Most likely though, if you don't remember it, you probably didn't change any of the default configuration values, in which case, it won't be the cause of the problem here. I'm just thinking that if any of it was changed from its default values, I could replicate the changes on my end, test everything again, and see whether there might be something going on there that might be causing the problem (because those settings change the way that the cache works, and if things are suddenly and unexpectedly disappearing from the cache.. it's something worth investigating, in any case).

**Comment by mikeruss1** [comment] 2019-06-05 05:46
Memcached is available but I found it likely to reset too often. Indeed I know it reset around the time I had the problem with Cidram. In any event I know I havent given it the memcached configuration so it can't be that. 

⁣Regards.... Mike
World War 2 Cruiser Operations

**Comment by mikeruss1** [comment] 2019-06-07 16:39
Looks like the system reset twice today. 

⁣Regards.... Mike

**Comment by 737simpilot** [comment] 2019-06-10 07:18
I was just talking about layer 7 DDoS in another issue. And with that, how good is CIDRAM at actually logging each event should one encounter a layer 7 DDoS? Not saying that is what's going on here, but it raises an interesting point seen as how it appears multiple hits are missing the log.

**Comment by Maikuolan** [comment] 2019-06-10 07:41
> And with that, how good is CIDRAM at actually logging each event should one encounter a layer 7 DDoS?

In practice, I haven't actually ever tested how effectively CIDRAM could cope in that scenario. However, in theory: Not good at all. *Refer: "[Will CIDRAM protect my website from DDoS attacks?](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#DDOS_ATTACKS)"*.

Whether L7, or whether any other kind of DDoS attack; If DDoS attacks are a serious concern, I would recommend investing in a dedicated DDoS protection solution (Cloudflare is likely still the most popular at the moment AFAIK, but there are quite a few such services available nowadays).

**Comment by Maikuolan** [comment] 2019-09-19 15:50
*Closing as resolved.*

**Closed as completed** 2019-09-19 15:50 UTC
Labels: Question, Resolved
