### ISSUE TITLE
UA blocks aren't working

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#20] opened 2017-01-16 17:16 UTC
Since Zap's site is down again I'm commenting here. I just installed the update to the ancient UA blocks module and I changed my UA to a version 3 of Firefox and I still don't get blocked. Not sure what is going on here. ZBblock works to block me however.

**Comment by Maikuolan** [comment] 2017-01-16 23:36
*Related thread/discussion at Spambot Security: http://www.spambotsecurity.com/forum/viewtopic.php?f=61&t=4042*

The site seems to be back online again now, and the discussion there about this problem already has a number of replies and more information than the issue here about this problem, so for now, I'll reply there in favour of replying here.

However, I'll keep this issue *open* until the problem has been resolved, for the sake of synchronicity and in case the site goes down again (and also because I'm not entirely sure whether macmathan has a registered account at Github, and it would be good to give him the opportunity to reply, too). We'll continue the discussion here if the site goes down again.

**Comment by Maikuolan** [comment] 2017-01-22 18:30
Marking as resolved and closing (solution provided via SBS; no reported problems thereafter). Will reopen as per necessary if the problem is reported to be persisting.

**Closed as completed by Maikuolan** 2017-01-22 18:30 UTC
Labels: Resolved, Support
