### ISSUE TITLE
Infractions on Bypass

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#449] opened 2023-04-01 16:42 UTC
This might not be worth fixing unless it is hiding other problems

I have a bypass to reduce the signature count for a Windows NT6 UA

User agent: Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36 
Signatures count: 1 
Signatures reference: bobuam.php:L138, bobuam.php:L161, custom_mods.php:L23 
Why blocked: Suspected bot or scraper probe, Outdated browser (C), Vista bypass! 
Infractions: 2

the Sig count has been correctly reduced to 1, however the Infractions count has been incremented by 2
repeated and Infractions went up to 4.

**Comment by Maikuolan** [comment] 2023-04-01 16:49
Confirmed.

About to get some sleep for the night, but I'll work a on fix for this in the morning.

Definitely something that needs to be fixed, because if the total infractions reaches the minimum threshold necessary for a ban to occur, I can foresee someone potentially being banned seemingly immediately, without the forewarning provided by being blocked (as someone would normally be blocked before being banned, but the bypass, by reducing the signature count, presumably in most cases to zero, would prevent the block occurring, but by not likewise reducing the total number of infractions, would not prevent bans from occurring).

Thanks for spotting this. :-)

**Comment by Maikuolan** [comment] 2023-04-02 06:44
Should be fixed now. :-)

**Closed as completed** 2023-04-02 08:34 UTC
Labels: Bug, Fixed
