### ISSUE TITLE
Whitelisting in custom .dat not taking precedence

### ISSUE THREAD

**Issue by Gaffnet** [CIDRAM/CIDRAM#7] opened 2016-04-02 11:58 UTC
Hi, Maikuolan

I needed to whitelist a few EasyCron IPs that are hosted within OVH IP ranges but the whitelisted IPs specified in the ipv4_custom.dat doesn't seem to have precedence over blocked ranges in ipv4.dat.

In my case, I whitelisted 142.4.201.54/32 in ipv4_custom.dat but it remains blocked due to the 142.4.192.0/19. range specified in ipv4.dat.

**Comment by Maikuolan** [comment] 2016-04-02 13:33
Thanks for reporting this. :-)

The reported behaviour is not meant to occur, and I've replicated the problem on my end, so, I can confirm this as being as bug.

I'm investigating it now, to try to determine the cause and make the necessary changes. I'll reply here again when I've got it figured out.

**Comment by Maikuolan** [comment] 2016-04-02 14:27
Hi @Gaffnet,

I've just committed some changes to `functions.php` that should solve the problem. Could you test this and let us know whether it solves the problem? Cheers. :-)

(PS, extra glad you reported this problem, because I don't think the problem was precedence, but rather, that the whitelisting didn't seem to be being triggered at all, regardless of the precedence. It must've been a bug that I'd introduced at some point recently I imagine, because I'm certain I recall whitelisting working fine when I'd first introduced it, but, anyhow, in any case, it should work properly now; local testing of the changes on my end seemed to have resolved the problem, at least).

**Comment by Maikuolan** [comment] 2016-04-02 14:31
(PPS, that's 3 bugs you've found so far, which means 3 bugs fixed, assuming that these latest changes resolve this latest bug found; this is definitely helpful and useful). :+1:

**Comment by Gaffnet** [comment] 2016-04-02 15:25
I'm glad I can be of some help. :)

I blacklisted my IP in ipv4.dat, then whitelisted the same IP in ipv4_custom.dat and my site was accessible.  I removed the whitelist entry from ipv4.dat and was blocked from accessing the site.

Looks like everything's good. :+1:

**Comment by Maikuolan** [comment] 2016-04-02 16:11
Awesome. :-)

**Closed as completed by Maikuolan** 2016-04-02 16:11 UTC
Labels: Bug, Fixed
