### ISSUE TITLE
Version 2 question

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#219] opened 2021-05-04 15:56 UTC
in the process of installing v2 and there seem to be some modules missing from the Updates page?

BAD TLDs
Optional UAs
Baidu
HTTP version
Yandex

there were some more but not ones that I use.
Also having "failed to install" on a couple - TOR and Cloudfare. I suspect this is a timeout issue as it took a while to get Bobuam to install. Will try again at a different time.

**Comment by mikeruss1** [comment] 2021-05-04 17:35
producing a block OK ...
the Access Denied page has this when recaptcha should not be offered
{recaptcha_api_include} and
{recaptcha_div_include}
I am using my own custom page for the block which is a few years old ... maybe out of date for v2?

forget it found it
SB {captcha_api_include

**Comment by Maikuolan** [comment] 2021-05-05 01:32
> forget it found it
> SB {captcha_api_include

Yep. :-)

I renamed a few of the template variables when I added HCaptcha support recently, so that those variables wouldn't seem quite as tightly coupled to the existing reCAPTCHA implementation (so, for example, renaming "recaptcha_api_include" to a more neutral sounding "captcha_api_include").

> in the process of installing v2 and there seem to be some modules missing from the Updates page?

Are you installing from the latest tagged release, or from the latest available commit? There were some changes introduced early last month (so, a few commits back now, but still a little more recently than the latest tagged release), which affect modules a little. If the former, try first running "update all" on whatever components are showing as having updates available (e.g., CIDRAM core, front-end, etc), and after updating, reload the update page, and check whether the modules have reappeared and become available again.

**Comment by mikeruss1** [comment] 2021-05-05 07:57
no updates shown as available, using as follows

CIDRAM Core | 2.6.0-DEV+21120596


CIDRAM Front-End | 2.6.0-DEV+21120494

Common Classes Package | 2.6.0.1




-- | --

**Comment by mikeruss1** [comment] 2021-05-05 08:06
dont know if related but tried repair all and noticed a problem with English

l10n/en – Failed to deactivate!
l10n/en – Repair process completed. +0 bytes | -0 bytes | 0.007
l10n/en – Failed to activate!

**Comment by Maikuolan** [comment] 2021-05-05 10:42
> CIDRAM Core | 2.6.0-DEV+21120596
> 
> CIDRAM Front-End | 2.6.0-DEV+21120494
> 
> Common Classes Package | 2.6.0.1

Well, all of those are the current latest versions, so I guess, that mustn't be the problem then.

Also, at my end, all the modules are fully listed, including the ones you mentioned above as being missing at your end. So, I'm not quite sure currently what's going on there. I'll do some more debugging at my end though and let you know if I'm able to come up with anything.

> dont know if related but tried repair all and noticed a problem with English
> 
> l10n/en – Failed to deactivate!
> l10n/en – Repair process completed. +0 bytes | -0 bytes | 0.007
> l10n/en – Failed to activate!

Seen that happen before, and no idea why it's still happening, since I've tried fixing it a number of times already, with the problem seemingly disappearing at my own end and being seemingly properly solved when I test for it, only to have it then be reported that it's still seemingly happening for some users.

I wouldn't worry too much though, since the problem is really only an aesthetic one: Since the front-end updates page is only supposed to have the ability to activate or deactivate signature files and modules, and since language data is neither a signature file nor a module, the front-end updates page "fails" to activate or deactivate it. The failure itself doesn't have any consequences, but demonstrates a bug in the sense that it shouldn't be trying to activate or deactivate language data in the first place (since, which language data is "active" or "inactive" mostly depends on your configuration settings; i.e., which language you've set for CIDRAM).

**Comment by mikeruss1** [comment] 2021-05-05 10:56
Sorry!
The installation was a cold one, directly from the zip. Just copied auxiliary.yml and custom sigs from version 1 and modded config.ini to copy and paste my settings.

**Comment by mikeruss1** [comment] 2021-05-06 09:29
tried reinstalling with no changes - exactly the same problem. After Bobuam I only have
Optional cookie scanner module
Optional security extras module
Microsoft Azure IPv4 blocklist
the themes
Tor

**Comment by Maikuolan** [comment] 2021-05-07 15:49
Had been planning to revisit this today but didn't end up getting time for it, sorry. Earmarked for tomorrow. :-)

**Comment by mikeruss1** [comment] 2021-05-07 17:27
no pressure - thank you.

**Comment by mikeruss1** [comment] 2021-05-09 13:44
tried the recent update for #222, no change, modules still missing

**Comment by Maikuolan** [comment] 2021-05-09 14:18
Removing *Question* label. Adding *Bug* label. Have successfully replicated the problem (and yeah.. the problem is not something normal/expected). Still trying to figure out the cause currently.

**Comment by mikeruss1** [comment] 2021-05-09 15:07
That's a relief it wasn't me

**Comment by Maikuolan** [comment] 2021-05-09 15:59
Figured it out. Preparing commits now.

**Comment by Maikuolan** [comment] 2021-05-09 16:17
Done. Try first updating the front-end, then reload the updates page. Everything should be working properly again. :-)

**Comment by mikeruss1** [comment] 2021-05-09 16:27
yes fine thanks. You are in Australia ? Given up sleeping?

**Comment by mikeruss1** [comment] 2021-05-09 18:03
ready to implement v2.
I have ver 1 in cidram folder and v2 in cidram2. I was going to switch folder names then thought it might be ready to do a cache update which might not go well. Do I do best to put v1 into maintenance mode, wait a few secs, then switch folder names?

**Comment by Maikuolan** [comment] 2021-05-10 01:27
Depending on the exact process for the switch, maintenance mode may or may not necessarily be helpful (i.e., if deleting one of them before moving in the other, during that interim between the deletion and the move, since there wouldn't be anything there at all, whether enabled or disabled would become a moot point). If renaming each, and not deleting anything until after everything has been renamed, then maintenance mode could be helpful. To be doubly sure though, it would probably worth enabling it on both of them before the rename, then disabling it on the remaining installation after everything else is already done, in case of any unexpected hiccups along the way. But yeah, switching folder names should do the trick.

**Comment by mikeruss1** [comment] 2021-05-10 16:15
thanks - decided to change the require to point to cidram2 - thought its a bit cleaner. No probs so far.

**Comment by Maikuolan** [comment] 2021-05-11 14:58
(Closing since fixed and resolved).

**Closed as completed by Maikuolan** 2021-05-11 14:58 UTC
Labels: Bug, Fixed
