### ISSUE TITLE
Display - encoding small visual issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#107] opened 2019-04-22 20:03 UTC
I see a lot of those kind of files in the logs display:

For example:

> com/��+�����ļ���.zip

**Comment by DanielRuf** [comment] 2019-04-23 05:08
Hi,

Please provide more information like the used version / commit, the encoding (utf8 or different) of your logfile and so on.

**Comment by eurobank** [comment] 2019-04-23 06:09
Latest version of everything, default encoding.

**Comment by DanielRuf** [comment] 2019-04-23 07:30
> default encoding

You can check this in Notepad++ or most other IDEs / editors.
Seems like some file does not unicode / utf8.

**Comment by eurobank** [comment] 2019-04-23 07:37
Same thing, but see a sample, it seems Chinese ?

> ID: 1496
> Script Version: CIDRAM v1.12.0
> Date/Time: Sat, 20 Apr 2019 12:10:30 +0300
> IP Address: 118.24.240.166
> Signatures Count: 1
> Signatures Reference: 118.24.0.0/15
> Why Blocked: Cloud service ("Shenzhen Tencent", L12312:F0, [CN])!
> User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)
> Reconstructed URI: https://www.website.com/οΏ½Β½οΏ½οΏ½ΔΌοΏ½οΏ½οΏ½.tar.gz

**Comment by DanielRuf** [comment] 2019-04-23 07:40
> Why Blocked: Cloud service ("Shenzhen Tencent", L12312:F0, [CN])!
> User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)
> Reconstructed URI: https://www.website.com/οΏ½Β½οΏ½οΏ½ΔΌοΏ½οΏ½οΏ½.tar.gz

This is interesting. Seems the log entry creation does not properly handle these.

**Comment by Maikuolan** [comment] 2019-04-23 07:42
If "�" (`\xEFBFBD`, `\uFFFD`) is appearing in logs, I agree, that it's most likely due to an encoding problem (i.e., currently used encoding not recognising the actual character properly, so using the unicode replacement character instead).

CIDRAM uses UTF-8 (without BOM) by default. Theoretically, it's possible, that if a request includes request headers that aren't recognised properly by CIDRAM for whatever reason (maybe the request is using an encoding that isn't compatible with, or can't be translated to UTF-8), we would see these types of results in logs. (Not sure whether that's exactly what's happening here; I haven't looked into it yet; But, it's the first thing that comes to mind, anyway).

**Comment by eurobank** [comment] 2019-04-23 07:46
Searched all the logs, and all such logs are related to some Chinese blocks. So i guess it is Chinese character set related ?

This not a problem, just visual.

**Comment by Maikuolan** [comment] 2019-04-23 07:48
> CIDRAM uses UTF-8 (without BOM) by default.

(Or *should*, at least. All L10N files, for example, use BOM-less UTF-8, and whenever I edit any code, or make any changes, I always set my own editor's encoding to BOM-less UTF-8. All HTML output, too, specifies `charset=utf-8` via the `Content-Type` meta tag, so *should* be using UTF-8 encoding when rendered by browsers. But, I'll check this out more closely shortly).

**Comment by Maikuolan** [comment] 2019-04-23 07:50
> So i guess it is Chinese character set related ?

That's what I'm currently thinking, at least. I'll try to confirm this though.

> This not a problem, just visual.

Still.. I'm glad you've mentioned it. Maybe not a problem for us specifically, but could be a possible bigger problem for potential Chinese CIDRAM users in the future, if there's some encoding problem relating to Chinese output preventing them from reading their own logs properly. :-)

**Comment by Maikuolan** [comment] 2019-04-23 07:57
Using Notepad++, saving the problematic data in question, to a new file, using UTF-8:

`οΏ½Β½οΏ½οΏ½ΔΌοΏ½οΏ½οΏ½.tar.gz`

Converting it to Big5 produces garbage data, so I don't think it's Big5. Converting it to GB2312 produces something that looks valid, at least:

`慰螐陆螔陆慰螐陆慰螐陆螖螌慰螐陆慰螐陆慰螐陆.tar.gz`

Putting it through a translator produces nonsense, so I don't think it means anything. But, it is definitely Chinese glyphs, at least. So, possibly the request used GB2312.

**Comment by Maikuolan** [comment] 2019-04-23 08:06
Yeah.. I think the cause of the problem is an incompatibility between UTF-8 and GB2312.

As a very simple way to test this, creating an HTML file containing the following:
```HTML
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
οΏ½Β½οΏ½οΏ½ΔΌοΏ½οΏ½οΏ½.tar.gz
</body>
</html>
```

Produces (as expected) the problematic data:
![test1](https://user-images.githubusercontent.com/12571108/56564867-95654600-65e1-11e9-8823-0482ce7c80a4.png)

But, when we change `charset=utf-8` to `charset=gb2312`:
```HTML
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
</head>
<body>
οΏ½Β½οΏ½οΏ½ΔΌοΏ½οΏ½οΏ½.tar.gz
</body>
</html>
```

It produces the correctly encoded string:
![test2](https://user-images.githubusercontent.com/12571108/56564869-95654600-65e1-11e9-8c78-ac644a944100.png)

**Comment by Maikuolan** [comment] 2019-04-24 04:55
I've got an idea for a "fix", but it isn't perfect. Basically, writing a new class for guessing the most probable encoding of a string of bytes, based on (1) its conformity to the constraints imposed by an encoding, and on (2) occurrence/repetition/frequency of expected and commonly found byte sequences (or lack thereof) within strings belonging to an encoding.

If the guessed encoding doesn't match UTF-8, attempt to use `iconv()` to convert the string from the guessed encoding to UTF-8. If the conversion succeeds, use the converted bytes instead of the original bytes, thus "normalising" all data to UTF-8.

This should occur when rendering log data to be displayed at the front-end, but should not occur when storing log data. The reason is that currently, the mechanism for storing log data stores that data in its original/raw state, without performing any conversions or changes otherwise to that data. This is useful for having a better understanding of the nature of the blocked request, as it was in its original state. The moment that any transformation or conversion occurs, we could potentially lose that information, and if it occurs during (or prior to) the storing process, that loss becomes permanent. However, conversion during rendering for display makes sense, so that the information is more human-readable, intelligible, etc. In particular, I'm thinking that it would make sense to perform such conversions/transformations when using "fancy" formatting to display log data (seeing as this is primarily intended to make log data easier to read, to access, to understand, etc), but would not make much sense during "simple" formatting to display log data (seeing as that with "simple" formatting, we would normally expect to see that data in its raw state).

I'm thinking that this should probably only be done with "fancy" formatting, and not with "simple" formatting.

It's definitely something within my capacity to do, and would probably work as expected in this specific case.. but I couldn't guarantee that it would work in every case, and could potentially lead to strange, unexpected results in some cases, due to the nature of attempting to automatically guess character encoding, and due to that there isn't any one, particular, agreed upon method for correctly guessing character encoding.

As an example of some of the potential problems to be expected: [stackoverflow.com->euc-jp-or-gb18030-text-file](https://stackoverflow.com/questions/32963694/euc-jp-or-gb18030-text-file).

Already have a solid plan on how I could go about doing this, so I doubt it would take me too long to finish it and to implement it. But, I haven't started yet, because I'm not quite sure yet whether it would be worthwhile.

So.. Opinions invited. In particular: Do you think it would be worthwhile, or not worthwhile..?

**Comment by Maikuolan** [comment] 2019-04-25 10:11
Might've found a better way to approach this.. Will reply again a little later.

**Comment by Maikuolan** [comment] 2019-04-25 15:23
@DanielRuf Detecting whether a string is valid UTF-8 (and therefore, whether encoding normalisation is required) can be done easily with regular expressions. Various other types of character encoding have varying degrees of ease/difficulty involved.. there are some I could do; others, I would need to research a little more. But, I'm not sure now about using `iconv()` in this way anymore, due to that I've been doing some testing and have been finding inconsistencies in how `iconv()` is implemented at different systems, and I'm not sure how reliable it is for the purposes of converting between different character encoding.

Alternatively, I could change the logs page as such, that when non-UTF-8 data is detected, that some kind of warning or notice is displayed alongside that data, to let the user know that the encoding of that data isn't UTF-8; maybe also doing an ASCII-to-UTF-8 conversion for the affected data (which wouldn't usually accurately reflect the intended rendering, but would, at least, avoid replacement characters appearing on the page).

Not exactly a perfect fix, but a consistent and predictable fix. Thoughts..?

**Comment by Maikuolan** [comment] 2019-04-29 08:15
Since the latest commit, for log data that uses the wrong encoding, if an alternative encoding for that data can be found, and if it seems to be correct as best as we can tell, CIDRAM will display it underneath the wrongly encoded data.

As an example of what this should look like on the logs page:

![example](https://user-images.githubusercontent.com/12571108/56882086-1797b380-6a95-11e9-964a-62720deff0d5.png)

It should be able to successfully find something correct enough to be worth displaying for about ~72% of the time that this type of wrongly encoded data appears. I will try to improve on this eventually, when I can figure out how to do that, but for the moment, I'm satisfied enough with that number to call this bug "fixed" (for the most part). The logging mechanism is still storing the actual bytes involved correctly anyway; The bug in question is just a matter of being able to correctly display the characters that the client intends for those bytes to actually refer to. Considering also, that as of today, [about ~93.4% of the web uses UTF-8](https://w3techs.com/technologies/details/en-utf8/all/all) nowadays anyhow, effectively making UTF-8 the *de facto* standard for the web, I don't consider the remaining ~28% of the time that it isn't able to successfully find something correct enough to be worth displaying to be a *particularly* high priority. It'll never be an absolute 100% anyway, due to bots/scripts/etc intentionally sending garbage data to servers (i.e., meaningless bytes that don't correspond to any encoding and aren't intended to be rendered as meaningful characters anyway), and due to the existence of certain, specific outdated encodings that consider almost any sequence of bytes to be valid, and which, without the help of additional context or external factors, are mutually indistinguishable from each other. But, that said, if I can find ways to improve it further, to maybe raise the number a little higher, I'll definitely do that.

Marking as fixed. Let me know if there are any new, unexpected problems, or anything like that. :-)

**Closed as completed** 2019-04-29 08:19 UTC
Labels: Bug, Fixed
