### ISSUE TITLE
CIDRAM API

### ISSUE THREAD

**Issue by dev-101** [CIDRAM/CIDRAM#47] opened 2017-12-01 09:19 UTC
This is not an issue, just some thinking...

Could we add a simple php API, so to call it, in such a way that we can more easily integrate CIDRAM with existing systems in a stack, without actually modifying CIDRAM core (as that would require constant monitoring for changes etc.).

So, instead of placing CIDRAM the usual way, and make it work it's magic, we can call it's "external" function (verbose example follow):

> me: "Hey, CIDRAM, can you check this IP (request) for me?"
> CIDRAM: "Ok, here's what I found..."

It can then return result in json or whatever format, for example, if IP is clean, return something simple like "pass", "not blocked" or whatever (even blank result would be ok).

In case it has found something, it will return appropriate field, for example cloud:true, or bogon:true, sfs:true, you get the idea.

Then, we can, instead of usual call for loader.php, simply include CIDRAM as any other php file, and call it's testing (api) function instead. edit: in fact, we can leave that as it is, just set it to work in "api" mode (not blocking anything on it's own).

What do you think?

As I explained in recent (unrelated) issue, I do not use it yet, because I have to adapt it to my current stack in some way.

Thanks

**Comment by Maikuolan** [comment] 2017-12-01 10:50
Shouldn't be *too* hard to build something like this. Strictly speaking, we've already got a test function built into CIDRAM, so, we're *kind* of halfway there already (needed this function in order for the front-end IP test page and front-end IP tracking page to function correctly as intended):

In the `frontend_functions.php` file:
```PHP
/**
 * Simulates block event (used by the IP tracking and IP test pages).
 *
 * @param string $Addr The IP address to test against.
 * @param bool $Modules Specifies whether to test against modules.
 */
$CIDRAM['SimulateBlockEvent'] = function ($Addr, $Modules = false) use (&$CIDRAM) {
 ...
};
```

But if we were to call this test function after CIDRAM has already finished executing as a form of API, the way that CIDRAM cleans up after it finishes would probably need to be modified somewhat, due to that currently, it completes removes itself from memory after it finishes executing, in order to free up as much memory as possible to be reused by whatever comes after it (in the `loader.php` file, right at the end of it):

```PHP
    /** Unset our working data so that we can exit cleanly. */
    unset($CIDRAM);
```

Of course, ever since the past few versions, I've considered any future significant modifications to the loader to be backwards-incompatible changes, at least to some extent, due to that the internal front-end updates page never touches the loader, and only updates everything else (specifically, everything in the vault). *One minor exception being, of course, the WordPress version of CIDRAM, which also updates the plugin information for itself, to reflect any version number changes in the WordPress plugins dashboard as necessary.* There may be other ways of going about this though, too.

Anyway, it's a good idea. I'll have a better think about it, to consider what possible ways this could be done, what the best way might be and so on, and reply a little later.

**Comment by Maikuolan** [comment] 2017-12-03 15:09
Currently, I'm thinking the simplest and most straightforward way to go about doing this would be to not touch the core at all, but instead, to write a new, separate PHP file that can be inserted alongside the CIDRAM loader, but independent of it, as an alternative way to load everything (i.e., as callable API object or set of functions). To run CIDRAM as an API, whatever is needing to use it as an API, can just hook to this new, separate PHP file, instead of the loader, and then, instead of acting as a WAF, CIDRAM can act as an API, with the relevant callable API object or set of functions to be called whenever needed by the thing that it's hooked to. What do you reckon?

**Comment by dev-101** [comment] 2017-12-03 15:12
That is probably the best option, as it will be separated from the rest of the code.

:+1:

**Comment by Maikuolan** [comment] 2017-12-04 19:04
Very rudimentary, and doesn't really provide anything that didn't already exist in the package (beyond providing it in a slightly different way), but I've made a first commit for an API insert.

When you've got a moment, let me know what you thjink:
https://github.com/CIDRAM/CIDRAM-Extras/tree/master/api

**Comment by dev-101** [comment] 2017-12-04 20:42
Thanks Maikuolan, this looks great! :+1:

**Comment by Maikuolan** [comment] 2017-12-05 13:09
Marking as *Implemented* and closing. Let me know if any problems emerge, or if anything needs changing, and I'll reopen the issue. :-)

**Closed as completed by Maikuolan** 2017-12-05 13:09 UTC
Labels: Proposal, Implemented
