### ISSUE TITLE
IP's not being blocked i.e. 200 code not 403 as expected.

### ISSUE THREAD

**Issue by htjoe38** [CIDRAM/CIDRAM#126] opened 2019-06-06 14:29 UTC
Hi All.
As I do not use GitHub I hope I have this in the right place.

Two (so far) IP's not being blocked i.e. 200 code not 403 as expected.

I've had two IP's which should have been blocked but have not been, that is they have been given a 200 code not a 403 as I would have expected. However the "odd" thing is that my front page is 48k in size (not gzip'ed) but these two IPs were given 36k.  so I'm unclear what they were presented with.? With the current settings I would have expected a 403 code with zero bytes, which is my norm. for DigitalOcean and China.  When tested from the front end "IP Test" they both are flagged as being blocked. I do not use recaptcha. Both DigitalOcean and China are Instant-banned via my custom module.

When I used "Verify all" on the Updates page all was OK, and when I used the "Signature file fixer" page there was no problems found on the sig. files.

138.197.14.172  --  DigitalOcean, listed in IPv4.dat
60.191.38.77  --  China listed in CN_cidram.inc, and ipv4_isps.dat

Litespeed server
PHP 7.2.18
CIDRAM   1.13.0
ipv4.dat   2019.151.508
CN_cidram.inc 2019.155.660
ipv4_isps.dat  2019.151.508

Joe38

**Comment by Maikuolan** [comment] 2019-06-07 05:03
Hi Joe,

Did they hit an actual PHP page, protected by CIDRAM, or some other kind of resource?

**Comment by htjoe38** [comment] 2019-06-07 09:14
Hi Maikuolan

They both hit the home page, but nothing else - no css, jpg, or js.

Looking through the logs I have seen 60.191.38.77 several times before - the previous time was on the 3rd June when it got the expected 403, on the 4th of June. I updated CIDRAM sigs.  on the 5th of June it got a 200 as per the log extract below. Coincidence ?

60.191.38.77 - - [03/Jun/2019:23:05:30 +0100] "GET / HTTP/1.1" 403 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0"

60.191.38.77 - - [05/Jun/2019:18:44:21 +0100] "GET / HTTP/1.1" 200 36373 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0"

138.197.14.172 - - [06/Jun/2019:12:11:00 +0100] "GET / HTTP/1.0" 200 36361 "-" "Mozilla/5.0 (compatible; NetcraftSurveyAgent/1.0; +info@netcraft.com)"

**Comment by Maikuolan** [comment] 2019-06-07 10:26
Definitely weird.

I can confirm that both of the IPs concerned are still listed by the latest versions of the signature files, so definitely should be being blocked by CIDRAM. Testing locally on my end, via the IP test page, as well as by faking requests from the IPs concerned to my local test copy of CIDRAM, for both of the IPs concerned, still results in the usual "Access Denied" page and 403 headers.

If the requests hit actual, real PHP pages protected by CIDRAM, then I've got no idea at this time why they weren't blocked TBH. :-/

Specifying the names of the signature sections that contain the signatures responsible for blocking those IPs into the `ignore.dat` file would prevent them from being blocked, but it would do so for all requests; not just a few random, sporadic requests here and there.

Any recent error logs in the CIDRAM base directory?

**Comment by ghost** [comment] 2019-06-07 10:33
That looks like Apache logs, so a thought comes to mind.
Do you have any server side redirections in place? I.e. www subdomain to no subdomain or vice versa?
Those take place _before_ CIDRAM executes.

**Comment by dev-101** [comment] 2019-06-07 10:53
What software do you run on your server (e.g. WordPress or some other CMS)?
Do you use static caching (e.g. html)? If so, then CIDRAM cannot help you in such case, as it requires 'active' page processing.

**Comment by htjoe38** [comment] 2019-06-07 11:10
@Maikuolan  
no error logs, and all appears to be working OK
"Definitely weird." -- yes, which is why I've flagged it up here.

@macmathan
Yes - I have several 301's  I have SSL/TLS so a redirect from non-SSL, and I have four domain names pointing to the one website, so three have 301's to the main domain. But all of that has been working for a long time and nothing has been changed recently.

@dev-101
Wordpress which I've kept at 4.9.10 to avoid Gutenburg.!
I have wp-super-cache set to "simple" PHP mode so that CIDRAM will always run. And CIDRAM is catching lots every day, on cached and non-cached pages.

**Comment by dev-101** [comment] 2019-06-07 11:15
About Gutenberg, upgrade to latest WP and then install this plugin:
https://wordpress.org/plugins/classic-editor/

Since you are using LiteSpeed, check that your server is not actually doing any caching with it, that can override your WP completely. You can do a simple test to verify if any PHP is executed at all if you access your website as a guest/incognito. Also, check your .htaccess to see if there are no redirects, which can bypass PHP.

_edit:_ Ah, since it does work overall, then it is something else going on here.

**Comment by htjoe38** [comment] 2019-06-07 11:50
Thanks for your thoughts dev-101

I understand that some cache systems could bypass CIDRAM which is why I have wp-super-cache set to "simple" mode so that it always run PHP. I have made sure that Litespeed is not caching anything for that reason.

As mentioned to macmathan I do have a number of 301's set up in the .htaccess but it has been working OK for a long time and nothing has changed recently, with CIDRAM working just fine, with the exception of those two IP's.

**Comment by 737simpilot** [comment] 2019-06-10 07:06
My host uses Litespeed as well and I noticed a while ago all of a sudden some new plugin install into my WordPress site from Litespeed. I asked my host about it and told me that it was a caching plugin. Being thoroughly pissed that my host would install crap in my site without my approval I removed it and I had to set an htacces directive to stop it from ever installing again. Another thing is that I don't do any WordPress cache because that's messed my stuff up before. I also use CloudFlare so there's really no need, although my site loaded a hell of a lot faster. But I really don't care about page load time all that much on this site since it's just a shrine for my late cousin who passed away and nothing more. It's not really meant for everyone or something like a normal CMS, etc. 

So with that, you may have another cache going on there thanks to Litespeed and to see if that is installed check your plugins and any htaccess code changes. 

Do you have CIDRAM hooked via htaccess?

**Comment by htjoe38** [comment] 2019-06-10 10:39
``142.93.78.116 - - [09/Jun/2019:22:40:16 +0100] "GET / HTTP/1.0" 200 36373 "-" "Mozilla/5.0 (compatible; NetcraftSurveyAgent/1.0; +info@netcraft.com)"``

Another DigitalOcean IP which is blocked by CIDRAM -- but not on this occasion. As they clearly identify themselves - Netcraft - I shall add it to .htaccess and continue to monitor the logs.

When I used Netcraft dot com to test my website CIDRAM 403'ed it as expected.

**Comment by Maikuolan** [comment] 2019-07-12 06:08
*Possibly related (but not confirmed): #136.*

**Comment by eurobank** [comment] 2019-07-12 07:11
@htjoe38 what do you have set as "forbid_on_block" in CIDRAM config ?

**Comment by htjoe38** [comment] 2019-07-12 09:37
@eurobank
 "forbid_on_block"  is set to 403 Forbidden so they should get the Access Denied notice.
also "ban_override" is set to 403 so they should get a 403 but zero bytes when the "infraction_limit" is exceeded.

[clutching at straws]
I occasionally see 401 errors when Netcraft tries to access the site, is it possible that they are using mal-formed headers which is causing the server to respond before it gets as far as CIDRAM/Wordpress ?
[/clutching at straws]

**Comment by Maikuolan** [comment] 2019-07-12 11:12
> I occasionally see 401 errors when Netcraft tries to access the site, is it possible that they are using mal-formed headers which is causing the server to respond before it gets as far as CIDRAM/Wordpress ?

Hadn't thought of that before.. That's definitely a possibility though. At the very least, of the various status codes provided as options for when CIDRAM blocks a request, 401 isn't one of them, and there's nothing in CIDRAM whatsoever, there or elsewhere, that should be capable of producing a 401 status code in its own right.

For those that don't know: Although 403 is one of the status codes provided as options for when CIDRAM blocks a request, and although there are similarities between __*[401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)*__ and __*[403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)*__ status codes, there are some distinctions between the two that would make a 401 status code an inappropriate choice (e.g., the implication that the client can attempt to reauthenticate in order to gain access to the requested resource in the event of a 401, and the implication that reauthentication should be generally ineffective and pointless in the event of a 403).

Possibly, if the client is sending authorisation headers along with their requests (e.g., `http://username:password@example.com/`), and either the server isn't expecting any, or they don't match whatever the server expects, the server could quite possibly be responding before CIDRAM has a chance to do anything (seeing as CIDRAM would generally be executed upon a request made to a protected resource, and the server wouldn't be serving that resource to the client at all in the first place, given the unexpected or invalid authorisation headers, instead just serving an immediate 401 response without any resource returned).

**Comment by Maikuolan** [comment] 2019-07-12 11:15
(That all said though, although that could explain the 401 responses, it wouldn't necessarily explain the 200 responses).

**Comment by eurobank** [comment] 2019-07-12 11:21
@htjoe38 Could you please run your site against

https://webscanner.nintechnet.com/

and post here if you get a 403 or the test completes ?

**Comment by htjoe38** [comment] 2019-07-12 12:54
@eurobank
The https://webscanner.nintechnet.com/ gave --
  Error: The server return a 403 HTTP code
As it was using Hetzner Online GmbH CIDRAM blocked it, and as I get lots from that server I have made it an Instant Ban.
So all working as expected, which is what I see 99.99% of the time.
@Maikuolan
Thanks for your thoughts - as I can't see what headers are sent, and at that point I'm out of my depth I thought I'd mention it. Netcraft does seem to try things it's not supposed to do. And if Netcraft can do it then maybe hackers could as well. i.e. mess with headers to try to access the server in some way, before CIDRAM kicks in.?

**Comment by Maikuolan** [comment] 2019-07-14 09:09
> Netcraft does seem to try things it's not supposed to do. And if Netcraft can do it then maybe hackers could as well. i.e. mess with headers to try to access the server in some way, before CIDRAM kicks in.?

I'm wary of being potentially alarmist, considering that neither of us have actually seen which headers Netcraft et al are sending with the request, but I imagine that in theory, that could be something that's happening.

If that's the case though, there won't be much that CIDRAM could do about it, because, if the server is deciding how to respond to the request before the request touches PHP, then CIDRAM will never see it anyway, so will never be able have any say in the matter regardless. Though, that would also suggest that the server is doing something that it's *meant* to do; killing off unauthorised, malformed, and hacky-looking requests, that you wouldn't want to be serving up resources to anyway. In any case, if we wanted to change how those kinds of requests are handled by the server, we'd probably need to be using a server module or daemon of some kind to be able to do so, I think.

**Comment by htjoe38** [comment] 2019-07-14 10:37
> If that's the case though, there won't be much that CIDRAM could do about it, because, if the server is deciding how to respond to the request before the request touches PHP, then CIDRAM will never see it anyway, so will never be able have any say in the matter regardless.

Understood and agreed. I _suspect_ that it's a server thing, but there is no way (for me) of knowing.

Thanks for all your help and suggestions.

**Comment by Maikuolan** [comment] 2019-09-19 15:46
@htjoe38 Have you encountered any more of this behaviour since our earlier discussion here, or does it seem to have stopped? Just asking, because we haven't made any further progress on it here otherwise. If you're still seeing this same behaviour, then it's something we'll still need to deal with somehow, but if you haven't seen any more of this behaviour recently, it's possible it might've been some problem at the server which has since seen resolved externally, and we could probably close this issue then.

**Comment by htjoe38** [comment] 2019-09-19 20:56
@Maikuolan  I've not seen this happening again. Most odd.
So thanks for all your help and suggestions, and please feel free to close this issue.

**Comment by Maikuolan** [comment] 2019-09-20 03:03
You're welcome, and cheers. :-)

**Closed as completed** 2019-09-20 03:04 UTC
Labels: Resolved, Support
