### ISSUE TITLE
A question on Aux rules

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#591] opened 2024-05-19 19:10 UTC
what will happen if I have 2 rules, the first will turn off tracking, the second applies extended tracking.

it looks like the first (which is a higher priority) wins? but its tricky to test.

am I right in thinking that extended tracking = the old instaban?

**Comment by Maikuolan** [comment] 2024-05-20 04:35
> what will happen if I have 2 rules, the first will turn off tracking, the second applies extended tracking.
>
> it looks like the first (which is a higher priority) wins? but its tricky to test.

Applying options to IP tracking, whether they be default or extended, would be evident only when IP tracking is turned on (because the options to be applied affect the expiry time and infractions applied to an IP tracking entry, which is only relevant when IP tracking entries are being created in the first place). It's not so much that one has higher priority than the other, but rather that the options in effect won't matter when IP tracking is turned off, and applying them doesn't actually affect whether IP tracking is turned on or off, and forcibly enabling/disabling IP tracking likewise doesn't affect which options are to be applied.

You could then, hypothetically (though there wouldn't be much point to it), have rule A disable IP tracking, rule B change the options applied to IP tracking, rule C then reenable IP tracking, and the options applied at rule B would become evident for subsequently saved IP tracking entries, or, in the absence of rule C, or in the presence of some subsequent rule D/E/F disabling IP tracking again, not become evident.

> am I right in thinking that extended tracking = the old instaban?

Yep. :-)

*Some more context, for anyone interested (a bit of a TL;DR, and not necessary for actually answering the question posed by the issue, but maybe useful for those wanting to better understand the context):*

What "extended tracking" does is *mostly* the same as what "insta-ban" did in previous major versions of CIDRAM (though there've been various minor improvements made to the whole system overall over time since those previous major versions). I just don't want it to be labelled that way at the auxiliary rules page or elsewhere internally at the front-end anymore due to the risk that such terms could potentially be misleading for future new users regarding what it actually does (the same reason why I don't use terms like "perma-ban", either).

The term "insta-ban" was something originally inherited from ZB Block, where when an IP address was banned, it would typically be banned forever, unless/until whoever administrates the installation where said ban occurred decided to either manually remove said IP address from the file where said bans are listed or remove said file entirely from their installation (whereby it would be automatically recreated the next time a new ban occurred). If an action was considered as particularly heinous, instead of just counting the number of signatures triggered and enforcing a ban at the end of the execution chain when that count exceeded a particular number, a ban would be enforced immediately regardless of that count, hence an "insta-ban".

CIDRAM, on the other hand, doesn't truly ban *forever*, instead relying on its IP tracking system, comparing the number of infractions incurred by a given IP address against the configurable maximum allowed number of infractions to determine whether that IP address is "banned", and having expiration dates be applied to each IP tracking entry, thus ending a ban at the time that the IP tracking entry expires.

This is the better way to go IMHO, due to that IP addresses are regularly bought and sold between different networks and the near-inevitability of a formerly bad IP address being eventually reassigned to someone or something innocent and benign one day, where permanence would inevitably cause false positives and the requirement of additional maintenance work on part of whoever administrates any affected installations.

Because CIDRAM relies on the number of infractions recorded by the IP tracking system to determine whether an IP address is banned and doesn't do so permanently, it isn't viable to handle "insta-bans" internally the same way that ZB Block did. Instead, to produce a similar effect, CIDRAM induces a higher number of infractions for an action or request and with an extended expiration time, so that the number of infractions should, in theory, be large enough to "instantly ban" the IP address in question, and the expiration far enough away that it stays in effect for sufficiently long enough time.

Having the maximum allowed number of infractions be configurable is also a good thing, as it allows finer control of how CIDRAM behaves at websites for those administrating it, but the downside to it is that applying a static amount of infractions to an IP address at a given inbound request for any given actions no longer guarantees whether the IP address would or would not be banned in consequence to said actions, as it would depend on how that maximum has been configured. So, in that sense, just describing and labelling it as "extended IP tracking options" is better than describing or labelling it as "insta-ban", as it more closely describes what's actually happening behind the scenes and doesn't imply an absolute guarantee of a ban occurring. If I were to label it as "insta-ban", I could foresee someone reporting that "*it doesn't work, something is wrong!*" when they use it and yet find an IP address not being banned, due to having a maximum number of infractions be configured to an excessively high number.

On top of that, there's also the potential for caching problems getting in the way of things, seeing as IP tracking stores its entries in the cache, and we've seen how sometimes caching doesn't always work as intended, due to race conditions, misconfigurations, etc, so good to avoid implications of permanence in that sense too. '^^

That all said, I'm not nitpicky about semantics during normal discussion and conversation, and it's totally fine to refer to it however we each want when talking about it in issues and such such as here, as we each know what the other is referring to anyway, and as long as we're able to convey our intended meaning to each other without any problem, all is good. I'm just being a little nitpicky when it comes to the labelling and descriptions at the actual front-end itself, in order to avoid potential confusion as best as possible for new users which mightn't have the same depth of experience and background context as we do. :-)

**Comment by mikeruss1** [comment] 2024-05-20 06:19
thank you for the comprehensive answer !

so to be specific, working down the aux rules it hits a rule which says if the reason for a block is "Cloud service", then dont track.

the next rule says if the reason is "Protocol Denied" then apply extended tracking

if both are true it should apply extended tracking?

I think this isnt happening, but I would need more testing to be sure

**Comment by mikeruss1** [comment] 2024-05-20 07:44
tested as I thought .. (the UA of mike is blocked higher up in the Aux rules)
extended tracking is working
but this sequence ..
test2:
 Method: "WinEx"
 Logic: "All"
 Forcibly disable IP tracking: true
 Profile:
  If matches:
   UA:
    - "*mike*"
test:
 Method: "WinEx"
 Logic: "All"
 Enforce extended IP tracking options: true
 Profile:
  If matches:
   UA:
    - "*mike*"
   
the second test is ignored, the request is blocked, reported and logged but not tracked.

if only the 2nd test is present immediate 403, not logged, and banned

**Comment by mikeruss1** [comment] 2024-05-21 04:51
forget it, sorted. Have realised that extended tracking is dependent on the setting of IP Tracking. If I turn it back on then it works as expected. Sorry to waste your time!

**Closed as completed** 2024-05-21 04:52 UTC
Labels: Question, Resolved

**Comment by Maikuolan** [comment] 2024-05-21 06:10
All good. :-)
