### ISSUE TITLE
Sharing to mix.com lists "CIDRAM" as title for all shares

### ISSUE THREAD

**Issue by 100percentlunarboy** [CIDRAM/CIDRAM#80] opened 2018-07-03 16:49 UTC
## Issue
The social sharing network Stumbleupon shut down and was replaced by mix.com. Before stumbleupon shut down I imported my images/posts from stumbleupon to mix.com.

When trying to share an image to the network the image displays like this:

![cidram title on mix](https://user-images.githubusercontent.com/36624929/42232126-bee1dc2e-7eaa-11e8-931d-d35259e19f4e.jpg)

If you scroll through my collection here (listed below) you will see many examples where the tile of the share is listed as "CIDRAM" and the image is blank.

https://mix.com/chaos_coa/

### CIDRAM version used (if known, please also include the exact commit hash).
1.6.1

---

### Expected behavior
Image should share - listing the title of the blog post next to the image

### Actual behavior
Images share but all have the title changed to CIDRAM and no image is shared

### Steps to reproduce the behavior
Share image to mix.com
Import images from stumbleupon to mix.com

### Relevant logfile entry (if applicable).

ID: 7858
Script Version: CIDRAM v1.6.1
Date/Time: Tue, 03 Jul 2018 16:27:02 +0000
IP Address: 54.221.198.105
Hostname: rigby01.embed.ly
Signatures Count: 1
Signatures Reference: 54.220.0.0/15
Why Blocked: Cloud service ("Amazon.com, Inc", L10754:F4, [US])!
User Agent: Mozilla/5.0 (compatible; Embedly/0.2; +http://support.embed.ly/)
Reconstructed URI: https://loschaos.com/zelda-by-shalizeh/

ID: 7859
Script Version: CIDRAM v1.6.1
Date/Time: Tue, 03 Jul 2018 16:27:03 +0000
IP Address: 52.4.223.64
Hostname: ec2-52-4-223-64.compute-1.amazonaws.com
Signatures Count: 2
Signatures Reference: 52.0.0.0/11, functions.php:L1428
Why Blocked: Cloud service ("Amazon.com, Inc", L10449:F4, [US]), Fake Googlebot!
User Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
Reconstructed URI: https://loschaos.com/zelda-by-shalizeh/

ID: 7860
Script Version: CIDRAM v1.6.1
Date/Time: Tue, 03 Jul 2018 16:27:06 +0000
IP Address: 52.4.223.64
Hostname: ec2-52-4-223-64.compute-1.amazonaws.com
Signatures Count: 2
Signatures Reference: 52.0.0.0/11, functions.php:L1428
Why Blocked: Cloud service ("Amazon.com, Inc", L10449:F4, [US]), Fake Googlebot!
User Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
Reconstructed URI: https://loschaos.com/zelda-by-shalizeh/

Delete image from mix.com and try to share again:

ID: 7861
Script Version: CIDRAM v1.6.1
Date/Time: Tue, 03 Jul 2018 16:28:16 +0000
IP Address: 52.4.223.64
Hostname: ec2-52-4-223-64.compute-1.amazonaws.com
Referrer: https://mix.com
Signatures Count: 1
Signatures Reference: 52.0.0.0/11
Why Blocked: Cloud service ("Amazon.com, Inc", L10449:F4, [US])!
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Reconstructed URI: https://loschaos.com/zelda-by-shalizeh

### Troubleshooting

I have tried turning off block cloud services

I tried adding domain names / IP addresses from blocks to ignore.dat but the issue remains - "CIDRAM" listed as the title for all shared images from loschaos

Currently, I am able to share to mix.com from my other site offworlders but many of the images imported when switching from stumbleupon to mix have the issue where "CIDRAM" is the title and the share image is blank.

Sharing from offworlders does not seem to generate the same blocks - at least not when sharing one image (blocked on import from old service to new service)

When you disable CIDRAM the images share correctly and the issue goes away.

Any ideas?

Thanks!

**Comment by 100percentlunarboy** [comment] 2018-07-03 18:37
Cool... Thanks!

**Comment by Maikuolan** [comment] 2018-07-04 15:00
Should be fixed as of the latest commit. :-)

After you update, when you've got a moment, let me know how it goes.

**Comment by 100percentlunarboy** [comment] 2018-07-04 18:19
Hiya. Thanks for looking into this so quickly!

Ran the updates and tried again.

It worked once then started blocking all other attempts to use the service. 

Here are the blocks that show in the killed log on a consistent basis for each attempt to share an image:

ID: 8116
Script Version: CIDRAM v1.7.0
Date/Time: Wed, 04 Jul 2018 18:08:28 +0000
IP Address: 52.4.223.64
Hostname: ec2-52-4-223-64.compute-1.amazonaws.com
Signatures Count: 2
Signatures Reference: 52.0.0.0/11, functions.php:L1452
Why Blocked: Cloud service ("Amazon.com, Inc", L10453:F4, [US]), Fake Googlebot!
User Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
Reconstructed URI: https://loschaos.com/shepard-x-talizorah-vas-normandy/

ID: 8117
Script Version: CIDRAM v1.7.0
Date/Time: Wed, 04 Jul 2018 18:08:31 +0000
IP Address: 52.4.223.64
Hostname: ec2-52-4-223-64.compute-1.amazonaws.com
Signatures Count: 2
Signatures Reference: 52.0.0.0/11, functions.php:L1452
Why Blocked: Cloud service ("Amazon.com, Inc", L10453:F4, [US]), Fake Googlebot!
User Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
Reconstructed URI: https://loschaos.com/shepard-x-talizorah-vas-normandy/

ID: 8118
Script Version: CIDRAM v1.7.0
Date/Time: Wed, 04 Jul 2018 18:08:32 +0000
IP Address: 52.4.223.64
Hostname: ec2-52-4-223-64.compute-1.amazonaws.com
Referrer: https://mix.com
Signatures Count: 1
Signatures Reference: 52.0.0.0/11
Why Blocked: Cloud service ("Amazon.com, Inc", L10453:F4, [US])!
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
Reconstructed URI: https://loschaos.com/shepard-x-talizorah-vas-normandy


let me know if you need any further info...

**Comment by Maikuolan** [comment] 2018-07-04 23:49
Cheers.

I might need to take a closer look at them, to figure out why they're pretending to be Google. The bypass works on their originally cited UA, which means that the bypass isn't being triggered when they use different UAs (and I'm not super comfortable about mainlining a bypass for faked Google UAs, because that could expose protected websites to problems elsewhere).

Failing all else, the alternative, of course, would be to add an ignore rule for the default included Amazon ranges entirely, but that's not really ideal either, due to that it would expose protected websites to anything else connecting from Amazon too (and there's quite a few unrelated things on their ranges that  wouldn't be wanted).

Anyhow, I'll look into this further to see what can be done.

**Comment by Maikuolan** [comment] 2018-07-10 22:58
Had to create an account there to get any answers, unfortunately. Their site is a bit of a nightmare to figure out IMO too (their paste a URL tab wasn't working properly for me, and I couldn't actually paste anything into it), but eventually managed to figure out how to test their sharing feature, to see what actually happens when we share something there.

On one of my test servers, I created a file, `mix_test.html`, containing:
```HTML
<html>
Hello World.<br />
<img src="test.png" />
</html>
```

..and an arbitrary PNG created in MS Paint (just to give the test page some "content", to properly gage what happens during a share).

Checking the access logs of my test server immediately after testing their sharing feature, this is what I see from them:

```
54.204.20.249 - - [11/Jul/2018:06:46:45 +0800] "GET /mix_test.html HTTP/1.1" 200 57 "-" "Mozilla/5.0 (compatible; Embedly/0.2; +http://support.embed.ly/)"
54.204.20.250 - - [11/Jul/2018:06:46:45 +0800] "GET /favicon.ico HTTP/1.1" 200 1406 "-" "Mozilla/5.0 (compatible; Embedly/0.2; snap; +http://support.embed.ly/)"
52.4.223.64 - - [11/Jul/2018:06:46:45 +0800] "GET /mix_test.html HTTP/1.1" 200 57 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
52.4.223.64 - - [11/Jul/2018:06:46:46 +0800] "GET /test.png HTTP/1.1" 200 963 "http://[REDACTED]:81/mix_test.html" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
54.204.20.249 - - [11/Jul/2018:06:46:46 +0800] "GET /test.png HTTP/1.1" 200 963 "-" "Mozilla/5.0 (compatible; Embedly/0.2; snap; +http://support.embed.ly/)"
52.4.223.64 - - [11/Jul/2018:06:46:47 +0800] "GET /mix_test.html HTTP/1.1" 200 57 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
52.4.223.64 - - [11/Jul/2018:06:46:48 +0800] "GET /test.png HTTP/1.1" 200 963 "http://[REDACTED]:81/mix_test.html" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
52.4.223.64 - - [11/Jul/2018:06:46:48 +0800] "GET /mix_test.html HTTP/1.1" 200 57 "https://mix.com" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
52.4.223.64 - - [11/Jul/2018:06:46:49 +0800] "GET /test.png HTTP/1.1" 200 963 "http://[REDACTED]:81/mix_test.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
52.4.223.64 - - [11/Jul/2018:06:46:49 +0800] "GET /favicon.ico HTTP/1.1" 200 1406 "http://[REDACTED]:81/mix_test.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```

So, I can confirm, that they're definitely ghosting as Googlebot when content is shared with them, and there is no mistake here (i.e., we aren't mistakenly identifying some other bot or such thing, which is ghosting as Googlebot, as being them). Additionally, I can see from the access logs above that they're also ghosting as Google Chrome (i.e., pretending to be a browser, instead of correctly identifying themselves as mix.com).

At the very least, this is definitely bad netiquette, and unethical of them, IMO.

Will see what can be done and keep you posted about it.

**Comment by 100percentlunarboy** [comment] 2018-07-11 22:09
Thanks!

**Comment by 737simpilot** [comment] 2018-07-16 01:35
You may in fact will have to just get rid of the Amazon and Google verification in CIDRAM at reduced security in order for this to work. I use AWS S3 myself, but I have no trouble since it's a fetch and not an upload. Because on your end it's an upload there in lies the issue. CIDRAM is catching the upload. Make sense?  If you do get rid of Amazon and Google verification you might want to supplement your security with the free version of Ninjafirewall. I use CIDRAM and Ninjafirewall myself and it's a great combination.

**Comment by Maikuolan** [comment] 2018-07-16 13:06
So.. All my efforts to contact them have thus far been completely ignored, it seems.

With no explanation from them as to why they're spoofing/ghosting Googlebot and Chrome UAs, with them being unwilling to respond to my messages, and with no obvious solution in sight, my current thoughts are to just leave a warning in the documentation about them, that they're incompatible with CIDRAM's search engine verification, and leave it at that. Not really ideal, but not sure where else we could go with it if they're going to behave as they've been behaving and won't communicate with us (unless someone else has suggestions.. and I'm all ears).

Assuming we just leave it at that, @737simpilot's suggestion provided above would probably be the best way to go, I think, to ensure that it remains possible to share content to mix.com from your website (though doing so would obviously allow in other spoofed/faked search engine UAs too, of course).

**Comment by 100percentlunarboy** [comment] 2018-07-16 20:18
I understand. Thanks for looking into it! I used to get a lot of traffic from Stumbleupon before it was shut down and replaced by mix.com. I am not getting any traffic from their new site Mix so not willing to lower the shields for them...

**Comment by 737simpilot** [comment] 2018-07-17 05:29
I'm not sure how your website is setup, but would it be worthwhile to find a different image host? 

If you are using WordPress, I believe I saw an Amazon S3 plugin. I use S3 myself and it works great.  In fact, if you use the reverse proxy CloudFlare and have TLS enabled on your site, you don't have to worry about mixed content with your pics since CloudFlare automatically fixes mixed content based on some code from the HTTPS Everywhere project and something else. Albeit, you need to enable that mixed content option in CloudFlare. 

CloudFlare is great for security, but it has to be setup in such a way to protect your origin IP address. And that means you can't use your host's E-mail since the MX record will give away your origin IP address. I use gmail for my website forum myself to mitigate that.  If I grow I'll just switch over to Namecheap's E-mail offering. 

Anyway... You might want to explore Amazon S3, and the plugin. It's virtually free unless you have a massive amount of images and get/pull requests. 

Doing a quick search I found this plugin. https://wordpress.org/plugins/amazon-s3-and-cloudfront/

**Comment by Maikuolan** [comment] 2018-07-19 12:57
Documentation has been updated as of 051c37de6c304971370ce70a3c29a52f9d55d4cd to include mention potential compatibility problems between CIDRAM and Mix.com.

**Comment by Maikuolan** [comment] 2018-07-19 12:58
(Marking this as "resolved", rather than the usual "fixed" accompanied by "false positive" issues. More appropriate in this case, I think. Anyhow, marked and closing).

**Closed as completed by Maikuolan** 2018-07-19 12:58 UTC
Labels: False Positive, Resolved
