### ISSUE TITLE
False Positives?

### ISSUE THREAD

**Issue by Gaffnet** [CIDRAM/CIDRAM#2] opened 2016-03-14 11:36 UTC
Hello, 

I've been going over my CIDRAM logs and noticed a large amount of  IPv6 "Invalid IP" entries that, at least according to the User-Agents and the IP look-up info, _appear_ to be from mobile users or users from legit ISPs.  Below is a sample of the IPs and AS that are being blocked.

Admittedly, I'm not an IT guy so I'm unable to conclusively verify these false positives myself, or verify that they are in IP ranges used for business (hosting, cloud, non-user end point etc) services.

From what I can tell, none of these ranges are applicable in my [custom IPv6 config file](http://pastebin.com/18A7A1dv) (pastebin).

I'm using version 0.1.1 of CIDRAM with the IPv6.dat file that was updated March 12.

I appreciate any help you can give me.  Thanks!

**AS7922    2601::/20   Comcast IP Services, L.L.C.
AS20214 2601:580::/26   Comcast IP Services, L.L.C.
AS33650 2601:600::/26   Comcast IP Services, L.L.C.**
2601:058b:8404:5830:3d16:faef:1293:d0ab
2601:0603:0601:0978:c92f:8bde:f35c:6aaf
2601:0589:0101:0f0c:fcd9:f351:1023:425f

**AS852 2001:569::/33   TELUS Communications Inc.
AS852   2001:569:7530::/44  TELUS-HSIA-RCMDBC01**
2001:0569:753f:0800:b531:2d7b:8715:ff6d 
2001:056a:f6f0:0d00:a8d9:758f:f7a8:bbdc

**AS10796   2607:fcc8::/32  Time Warner Cable Internet LLC
AS11426 2606:a000::/32  Time Warner Cable Internet LLC**
2606:a000:674b:3800:3531:1784:2690:b775
2607:fcc8:e785:4a00:b966:af7a:0493:5bc6

**AS6167    2600:1000::/28  Cellco Partnership DBA Verizon Wireless
AS22394 2600:1001::/32  Cellco Partnership DBA Verizon Wireless
AS22394 2600:1001:b110::/44 Cellco Partnership DBA Verizon Wireless**
2600:1001:b11f:4ff5:c180:7036:6d7f:1e2f

**Comment by Maikuolan** [comment] 2016-03-14 12:16
Hi Gaffnet,

I'm actually really glad that you've reported this; Upon attempting to investigate this issue, I quickly discovered a bug in the code for calculating IPv6 CIDRs, caused by some excess spaces being where they shouldn't have been (I'm writing a fix for this bug right now, as I reply here).

Very sorry about this, any for not catching this bug sooner!

I'll reply here again shortly, after I've released the completed fix.

**Comment by Maikuolan** [comment] 2016-03-14 12:40
..And done.

I've released the fixed version (v0.1.2) just now; Could you try this, and let me know whether this solves the problem? Cheers. :-)

**Comment by Gaffnet** [comment] 2016-03-14 14:48
Super!

My sites are non-commercial, personal sites and aren't heavily trafficked so it may take me a day or two to accumulate enough data for a meaningful result.  But I'll report back ASAP.

Thanks again!

**Comment by Gaffnet** [comment] 2016-03-16 10:49
Hi Maikuolan,

Reporting back and so far, so good.   The IPs blocked by CIDRAM so far have been accounted for in the .dat files.  I'm not seeing any stray IPs or IPs from ISPs.

**Comment by Maikuolan** [comment] 2016-03-16 10:52
Awesome! :-)

In that case, I'll mark this issue as closed, but if any more problems do occur, let me know and I'll reopen it.

**Closed as completed by Maikuolan** 2016-03-16 10:52 UTC
Labels: Bug, Fixed
