### ISSUE TITLE
[v3] Captcha is not remembered

### ISSUE THREAD

**Issue by tnovak007** [CIDRAM/CIDRAM#389] opened 2023-01-26 07:54 UTC
Hi!
I used CIDRAM v2 without problems.

Now I made clean installation of CIDRAM v3 and have some problem with Captcha use.
I'm using invisible Re-captcha. In v3 configuration I set the same settings for Captcha I used in V2.

When request is blocked (I made for testing simple rule blocking my IP with "Mark for use with reCAPTCHA" and "Forcibly disable IP tracking"), Re-captcha let me pass after sec or so. But next request is again blocked and then passed.

Captcha log says:
IP address: 192.168.1.12 - Date/Time: 26.01.2023 08:40:46 - CAPTCHA State: Passed!
IP address: 192.168.1.12 - Date/Time: 26.01.2023 08:40:55 - CAPTCHA State: Passed!
IP address: 192.168.1.12 - Date/Time: 26.01.2023 08:41:01 - CAPTCHA State: Passed!
IP address: 192.168.1.12 - Date/Time: 26.01.2023 08:41:15 - CAPTCHA State: Passed!

Settings:
```
recaptcha:
 usemode: 2
 lockip: false
 lockuser: true
 sitekey: "xxx"
 secret: "xxx"
 expiry: 720
 recaptcha_log: "recaptcha.log"
 signature_limit: 1
 api: "Invisible"
 show_cookie_warning: true
 show_api_message: true
 nonblocked_status_code: 200
```
Can you please help me find out what I'm doing wrong?

Thank you!

**Comment by Maikuolan** [comment] 2023-01-26 08:32
By using the exact same configuration that you're using, I'm now seeing the same problem at my end, too. So, can confirm: It's a bug. Attempting to figure out the cause right now, and I'll push out a fix as soon as I do and then reply back here. Thanks for reporting the problem here. :-)

**Comment by Maikuolan** [comment] 2023-01-26 09:31
Found the problem. Should be fixed now. :-)

**Comment by tnovak007** [comment] 2023-01-26 09:37
Hi!

Yes, I just updated it and it seems to working well!

Thank you very much for this great tool and fast support!

**Closed as completed** 2023-01-26 09:38 UTC
Labels: Bug, Fixed
