### ISSUE TITLE
module_abuseipdb.php - reporting

### ISSUE THREAD

**Issue by szemet** [CIDRAM/CIDRAM#256] opened 2021-09-06 04:35 UTC
System information:
CIDRAM version used: 2.7.0
PHP version used: 7.2.34
SAPI used: cgi-fcgi
Extension➡Installed/Available
PCRE➡Yes (7.2.34)
cURL➡Yes (7.2.34)
APCu➡No
Memcached➡Yes (3.1.5) (not enabled)
Redis➡No
PDO➡Yes (7.2.34), {mysql, pgsql, sqlite}
Operating system used: Linux 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64

If report back is truned on in the abuseipb module (api key exists) gives the following error message:
```
Error at module_abuseipdb.php:L161 (error code 8): "Array to string conversion". Eep.. Something went wrong during "Reporting".
Error at module_abuseipdb.php:L161 (error code 2): "Illegal string offset '64.21.98.41'". Eep.. Something went wrong during "Reporting".
Error at module_abuseipdb.php:L161 (error code 8): "A non well formed numeric value encountered". Eep.. Something went wrong during "Reporting".
```
Still, the report gets submitted to abuseipb.com: https://www.abuseipdb.com/user/64066

**Comment by Maikuolan** [comment] 2021-09-06 06:08
Offhandedly, I'm not sure what's causing that error. I've briefly looked at the code which the error report cites as being the cause of the error (`module_abuseipdb.php:L161`), and I don't immediately see anything obviously wrong with it. But, there must be something I'm not seeing yet, because the error wouldn't occur otherwise. I'll look into it a little more deeply later today and reply back here with whatever I can find. :-)

**Comment by szemet** [comment] 2021-09-06 12:16
Deleted the AbuseIPDB cahce on the cache data page. It was fully empty before, but now it get populated by ips.
Waiting for reportable connections to come.

Edit: silly me, of course the cache was empty in the first place, the **expires** time is 1 hour.

**Comment by szemet** [comment] 2021-09-08 04:07
It seems, that the above (partial) chache.dat deletion fixed it. There are new submissions and no error log now.

**Comment by Maikuolan** [comment] 2021-12-21 15:09
I haven't noticed anything yet since back when we were last discussion this issue, and haven't been able to replicate the problem at the latest version of the codebase and module, so I'm guess, whatever the original root cause was, one of the changes made since then must've fixed it. I'll go ahead and mark this as fixed now and close this issue. We can always reopen it again later if the problem reappears.

**Closed as completed** 2021-12-21 15:10 UTC
Labels: Bug, Fixed
