### ISSUE TITLE
Fatal error  when running IP Test from loader.php 

### ISSUE THREAD

**Issue by frank4360** [CIDRAM/CIDRAM#112] opened 2019-05-16 14:03 UTC
Please use this template when reporting bugs, problems, issues, etc.

## Server information.
Hosted on shared server at ionos.fr (ex 1and1.fr)

### CIDRAM version used (if known, please also include the exact commit hash).
CIDRAM-CIDRAM-v1.12.0-18-ge7bc36c

### Signatures version (if known).
Latest downloaded May 2019

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
CGI/FastCGI

### PHP version installed (`<?php echo phpversion(); ?>`).
7.2.18

### Operating system used (`<?php echo php_uname(); ?>`).
Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux

---
## Issue
Trying to run IP Test on a new installation results in Fatal Error.
I am trying to set up CIDRAM on a very simple pure HTML web sit, prior to setting it up on a much more complicated Drupal 7 site. The site I am having the problem with does not use php but I created a php.ini file in which to place the "require", as the use of "prepend" in htaccess is not supported with the CGI.
 
### Expected behavior
Expected to write a known problem site to log file - initially I thought that the problem was that I had not created the log file. I created it and ran again - same result. I was not sure if I should be specifying a full path name, or simply create it in the "vault".
I removed the entry for a log file in the front-end set up and ran again - same result.

### Actual behavior
Fatal error: Uncaught TypeError: Argument 3 passed to {closure}() must be of the type integer, string given, called in /****************/Med-and-Mountain/CIDRAM/vault/rules_specific.php on line 107 and defined in /****************/Med-and-Mountain/CIDRAM/vault/rules_specific.php:30 Stack trace: #0 /****************/Med-and-Mountain/CIDRAM/vault/rules_specific.php(107): {closure}(Array, 18, ' ("Azure", L247...', 'Azure') #1 /****************/Med-and-Mountain/CIDRAM/vault/functions.php(405): require_once('/homepages/46/d...') #2 /****************/Med-and-Mountain/CIDRAM/vault/functions.php(487): {closure}(Array, Array) #3 /****************/Med-and-Mountain/CIDRAM/vault/frontend_functions.php(891): {closure}('23.100.232.233') #4 /****************/Med-and-Mountain/CIDRAM/vault/frontend.php(2855): {closure}('23.100.232.233', false, false) #5 /****************/Med-and-Mountain/CIDRAM/loader.php(102): require('/homepag in /****************/Med-and-Mountain/CIDRAM/vault/rules_specific.php on line 30

### Steps to reproduce the behavior
Specify a known problem IP address in IP test.

### Last known working version without this issue.

---

**Comment by Maikuolan** [comment] 2019-05-16 16:00
Thanks for reporting this. :-)

This is happening because of a wrong type hint added in a recent commit. Because of the particular error message in the fatal error you've quoted above, I've found, and can see where the problem is in the code, and I'll get a fix out for that within the next hour or so. Marking this as a bug accordingly, and I'll reply again after I push the fix (the wrong type hint is in the "default signature bypass" files, so, after I push the fix, simply updating those should fix the problem at your end).

I'm not sure why, but for whatever reason, the fatal error isn't occurring in my dev environment, which is partly why I hadn't noticed the problem earlier. I'll need to investigate that too, but that's a story for another day anyway.

**Comment by Maikuolan** [comment] 2019-05-16 16:36
(PS, for everyone's information: e7bc36cd2a4656fe7e31498d50d766660ec898ff belongs to the `v2` branch, and the `v2` branch isn't quite considered "stable" yet. What I mean by that, is that there'll likely be backwards-incompatible changes introduced in future commits pushed to `v2`, at least until `v2.0.0` is formally tagged and released. It should, however, still generally work as expected. So, if anyone wants to use the absolute cutting edge for where CIDRAM's development is heading, and doesn't care about backwards-incompatible changes, they can use `v2` right now. But, anyone that cares about backwards compatibility should stick to `v1` for the moment. `v1` is considered "stable". `v2` will be considered "stable", as soon as `v2.0.0` is formally tagged and released).

**Comment by Maikuolan** [comment] 2019-05-16 17:00
Fix has been pushed. :-)

**Comment by frank4360** [comment] 2019-05-16 18:40
Thanks for that.

I saw your CDIRAM on your Stopforumspam posts (I use the name pennycsf).

A question for you - do I have create the log file and if so should it be in the vault and do I need to specify the full path name?

Thanks

Frank


⁣Get TypeApp for Android ​

**Comment by Maikuolan** [comment] 2019-05-17 03:31
You're welcome, and nice to see you here. :-)

> A question for you - do I have create the log file and if so should it be in the vault and do I need to specify the full path name?

Logging is entirely optional. If you want CIDRAM to log all block events, then definitely, you should specify a log filename to use. Otherwise though, if you feel that logs won't be particularly useful for you, you can ignore the configuration directive for it, leaving it empty (in which case, CIDRAM won't log anything, but everything should still work all the same way otherwise).

Worth noting though, that if there are ever any false positives in the future (e.g., in the event that a user complains about being wrongly blocked), if nothing is logged (i.e., no log files), it can be very difficult to verify the validity of the false positive or complaint (whether it has actually happened, and whether CIDRAM is the cause, or whether the cause is something else entirely), and to determine what needs to happen, in order to fix the problem.

As to whether it needs to be in the vault: Because CIDRAM has been written in such a way, that it should only ever be able to create/modify files within its own vault, at this time currently, it can't write log files outside of its own vault. However, log files don't need to be in the base of the vault. You can, at your own discretion, have CIDRAM write its log files in the base of the vault, or if you'd prefer, have it write them to any subdirectory or subdirectories of your own choosing.

If you specify a subdirectory that doesn't exist, CIDRAM is able to automatically, recursively create any subdirectories needed in order to make it a valid path (which means that it's possible, if needed, for the specified log file path to be dynamic; useful for users that like automatically organising log files by year, month, etc).

CIDRAM interprets the specified path relative to its own vault. For example: If you specified something like "hello/world.txt", it would be interpreted something like "/root/public_html/CIDRAM/vault/hello/world.txt".

**Comment by Maikuolan** [comment] 2019-05-17 18:46
*Closing as fixed.*

**Closed as completed by Maikuolan** 2019-05-17 18:46 UTC
Labels: Bug, Fixed
