### ISSUE TITLE
Statistics issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#267] opened 2021-10-29 10:29 UTC
PHP 7.3.x CIDRAM Latest

It seems that the Statistics do not work correctly? While they are enabled (true). Start date today?

![Screenshot (2)](https://user-images.githubusercontent.com/4467158/139419860-c189f24d-ede4-453a-8617-c8378fe63ae9.png)

**Comment by Maikuolan** [comment] 2021-10-30 11:04
Was the cache recently cleared? Because the statistics are currently stored in the cache, clearing the cache will reset the statistics, too.

The "not tracking" message under the "requests passed" section is due to that capability not yet being coded in (I'm planning to implement some changes with v3 for how statistics are handled, which is why I hadn't yet coded in support for that statistics section yet).

**Comment by eurobank** [comment] 2021-10-30 11:08
No i cleared nothing. I just checked for an update, nothing else.

**Comment by Maikuolan** [comment] 2021-10-30 11:10
Hm, okay. I'll investigate this a bit further at my end to try to figure out what's going on there.

**Comment by eurobank** [comment] 2021-10-30 11:12
no worries.

**Comment by eurobank** [comment] 2021-10-31 09:27
It appears they clear every 2 (?) days. Now i have 60 block and todays date as Start Date.

**Comment by mikeruss1** [comment] 2021-10-31 10:59
I suspect the cache is getting contention problems and clearing. You can tell its happened when the start date is reset. I used to get that at my last hosting provider. It does better if you switch it to pdo or even better memcached.

**Comment by eurobank** [comment] 2021-10-31 11:01
@mikeruss1 My hosting provider doesn't mess in anyway in my hosting account. Not possible. And my cache size is not that big.

**Comment by mikeruss1** [comment] 2021-10-31 18:20
its caused by getting several page requests at more or less the same time, not related to cache size or anything the host does.

**Comment by eurobank** [comment] 2021-10-31 18:57
@mikeruss1 Nope. When we have heavy hits or anykind of excess load, we are just "limited" by CloudLinux and get an auto-warning if this continious.

This has nothing to do with hosting.

**Comment by mikeruss1** [comment] 2021-10-31 19:23
maybe depends on what they define as heavy hits, 2 or 3 within a second or so would do it for me, probably depending on what else was running if on a shared server

**Comment by 737simpilot** [comment] 2021-11-03 09:29
As a test you could rule out the hosting enviroment by running a WordPress site or something PHP driven in XAMAPP and run CIDRAM in XAMPP. Now request resources in this hosted XAMPP environment that'll sure get blocked by CIDRAM. Check your Stats. this time. Chances are they're there. 

I don't have this issue. I last cleared the cache last month. https://postimg.cc/K1Sqqxxf I also deploy Cloudflare that blocks an untold amount so thus the low block numbers you see. What Cloudflare doesn't block CIDRAM does. Pretty good combination thus far, but I have some 70 or 80 pages of Cloudflare firewall rules along with regular expression stuff for lack of the right word right now.

Out of curiosity, is your host a subsidy of Endurance International Group? The list is here: https://en.wikipedia.org/wiki/Endurance_International_Group Host Gator is one.

**Comment by eurobank** [comment] 2021-11-03 09:32
Guys i already asked my hosting (nothing to do with Endurance group) and their reply was that they never touch anything in my account.

Not a hosting issue. I will keep an eye open to this issue, to see when it happens.

**Comment by 737simpilot** [comment] 2021-11-03 09:38
> maybe depends on what they define as heavy hits, 2 or 3 within a second or so would do it for me, probably depending on what else was running if on a shared server

This _might_ be due to imunify360. That stupid firewall is just that, stupid. In one instance I checked a bad IP in CIDRAM and thus the POST of that IP in CIDRAM fired off my host's firewall (imunify360) and blocked me from my own FTP directory, cPanel, the whole nine yards with no par... (Golf terms.. LOL) After about 5 minutes I was allowed functionality again. I confirmed this was the case by talking to a head IT person with my host. (Don't remember the proper tech name for this support person).

The stupid here is that I can check IP after IP in CIDRAM that are all bad news and no blocks from my host, but this one IP I checked fired off the firewall. So right there you know they don't really use a comprehensive list of bad IPs anyway.

**Comment by 737simpilot** [comment] 2021-11-03 09:40
> 
> 
> Guys i already asked my hosting (nothing to do with Endurance group) and their reply was that they never touch anything in my account.
> 
> Not a hosting issue. I will keep an eye open to this issue, to see when it happens.

Doubt this is the issue, but is the CIDRAM folder's permissions 775?

Yes, of course a host will say that. They all will. Even though they do (the internal bot stuff) with your WordPress install and its htaccess. This was the case for me with two hosts and the behind my back installation of a Litespeed cache plugin. And I see my htaccess file is modified (or at least read, written, and same data written again) as  I monitor file changes in the FTP directory. And it's only the WordPress public_html folder, not my phpBB folder.

**Comment by eurobank** [comment] 2021-11-03 09:55
@737simpilot All folder and files are correct (644,755). Again, this is NOT a hosting issue and my hosting is totally honest. I assure you. I'm using them for 7 years now, with several plans and accounts. I'm hosting a lot of sites, Wordpress and others. 

Immunify could be an possibility, since it is server-wide, still i see no log about it. No Litespeed caching plugin, since it doesn't work well with the Forums i run and also puts load without any reason.

**Comment by Maikuolan** [comment] 2021-11-03 10:35
I haven't yet ruled out the possibility of there being a bug somewhere in CIDRAM responsible for this problem, so that's still possible. Busy past few days with work, so I haven't yet had the time to properly go through and analyse everything, to confirm whether or not that's the case. Sorry for that. I should have some free time coming up soon though. I'm also planning to begin work on v3 very soon, and I intend to rewrite the statistics system for v3 anyway, so there's a good chance that things will seem to work a little differently at that point anyway.

**Comment by eurobank** [comment] 2021-11-03 11:32
@Maikuolan No problem, not that important for me. I'm trying to find out when that happens. I think that would help a lot. Maybe it happens when i activate/deactivate some feature? Some component?

**Comment by eurobank** [comment] 2021-12-02 15:37
It seems that the statistics are taken from the logs (right?). So when i delete manually the logs or the logs are auto-rotated, the statistics are also modified/zeroed?

If so, then this is not an issue but by design. So all ok.

**Comment by eurobank** [comment] 2021-12-24 11:26
One thing i noticed today. my admin login was cleared (expired) and i had to re login. At the same time the Stats are cleared.

Maybe this give some hint when it happens.

**Comment by eurobank** [comment] 2022-02-21 13:27
I'm reopening this since i found that in my hosting account, all logs greater than 2 mb are cleaned (deteled) every 72 hours. 

So this is the cause of missing/wrong statistics.

Since apparently they delete files with extension LOG, could that be configurable? I mean the extension?

Thanks

**Comment by eurobank** [comment] 2022-02-21 13:28
Oh, just saw **it is configurable** .....

**Comment by Maikuolan** [comment] 2022-02-21 15:23
Thinking of changing some of the internal mechanisms behind statistics for v3 anyway, so we'll see how things go, I guess.

**Comment by Maikuolan** [comment] 2022-03-01 13:47
Have began working on this. Reopening the issue for the moment, to track progress. Will reply back again when I have something ready to test.

**Comment by eurobank** [comment] 2022-03-08 19:02
I think my hoster is not to blame for my statistics issue. Because the reset of stats is happening very randon. Not every 3 days, not every xxx standard days. It happens random. 

So, i would like to ask:

1. From where are the stats page get the stats?
2. Does CIDRAM clears the stats, how and when?

**Comment by Maikuolan** [comment] 2022-03-10 05:01
> 1. From where are the stats page get the stats?

Currently, statistics are stored alongside cache data. So, depending on the exact configuration for the CIDRAM installation in question (specifically, regarding "supplementary cache options"), the statistics may be stored either in a physical file, or by one of the various mechanisms supported by the cache (e.g., APCu, Redis, PDO, etc).

I'm investing ways to improve on that though, so possibly, things may be a little different (or at least, somewhat better) for v3.

> 2. Does CIDRAM clears the stats, how and when?

By design, no (i.e., it shouldn't). But considering what we've discovered here, I'm not completely writing off the possibility of there being some kind of bug somewhere causing the problem (although I haven't confirmed such a thing yet either).

It is possible, however, to manually/explicitly clear the statistics by way of the buttons provided by the front-end for the statistics and cache pages. But at least, CIDRAM shouldn't be deciding to clear anything on its own.

**Comment by eurobank** [comment] 2022-03-10 10:21
Ok, i do not use any APCu etc etc, so it must be on the folder of Cidram. What are the files, so i can check if they are REALLY cleared or some date issue is present.

**Comment by Maikuolan** [comment] 2022-03-10 11:22
`cache.dat` (in the vault directory) – It should all be in there as a block of serialised data. :-)

**Comment by eurobank** [comment] 2022-03-10 11:47
In that case .dat files are NOT deleted by my hoster. No way.

So it must be something else. How can i read (really view) that file? Is there any Windows software i can use? Because it is scrambled somehow.

**Comment by eurobank** [comment] 2022-04-05 16:12
No idea what changed but my Statistics seem to have stoped to clear. I see now from 18 March until today. 

On the other hand my tracking Ips are doubled from previous months (i see now around 1200 IPs), but this could be unrelated to Cidram.

**Comment by Maikuolan** [comment] 2022-06-19 16:16
Resolved by 185382349c10438b826873d0eeee32df4e5c8ee6, f565e4ff1a5c0641ad5bc6a2cb6c7d71b17665a2; Closing.

**Closed as completed** 2022-06-19 16:16 UTC
Labels: Resolved, QA, v3
