### ISSUE TITLE
Access to Macmathan backup location

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#186] opened 2020-07-25 17:19 UTC
have been discussing with David a problem I have in CIDRAM access to his repository is refused. Essentially this is a problem caused by my hosting company. Is there a very easy way of switching to using his backup?

really not worth a lot of work

thanks

**Comment by mikeruss1** [comment] 2020-07-26 13:17
reviewed your channels file and it looks like access to notabug for his backup should already work. It doesnt appear to?

**Comment by mikeruss1** [comment] 2020-07-26 18:15
in case it is easily changeable, the basic issue is that CIDRAM is using the host shared server address to access Macmathan's data, rather than the IP address of my domain . This looks to be very common on my host, as it has attracted appalling reviews on abuseIPDB. 

can you get hold of my domain IP, or is it down to the host configuration ?

**Comment by Maikuolan** [comment] 2020-07-27 01:27
Sorry for the delay. Wasn't feeling great yesterday so stayed off the machine for the day. :-)

> Is there a very easy way of switching to using his backup?

Generally, it should be possible to force CIDRAM to use specific channels, by telling it which channels to *not* use, via the `disabled_channels` configuration directive. But, I think I'll need to add his primary source to the list of available options for `disabled_channels` though, because currently, the only options listed are for GitHub, BitBucket, and NotABug (meaning, currently possible to disable any of those three, but not his primary source). I'll get onto that in a moment and will reply back here once sorted.

> can you get hold of my domain IP, or is it down to the host configuration ?

I assume, you mean the IP address it uses for outbound requests (i.e., when requesting updates), as opposed to the IP address it uses for inbound requests (i.e., the address your website resolves to)? (In my own experiences, I've found that for large, shared hosting scenarios, the two aren't necessarily always the same).

Regardless, either way, it's possible. But, if so, just slightly more complicated.

I'll get onto updating `disabled_channels` now, and I'll reply with more details after I've gotten that sorted out (since it should only take me a few moments to do anyhow). :-)

**Comment by Maikuolan** [comment] 2020-07-27 02:55
> I'll reply with more details after I've gotten that sorted out

..and done. :-)

So, with fetching your website's server's IP address: If it's just a matter of resolving the IP for inbound requests, that can be done with something like `nslookup your.domain.name`, or by using an online IP/domain checker (e.g., like the one at [ipinfo.info](https://ipinfo.info/html/ip_checker.php)), or by performing a whois requery. Lots of options. :-)

If it's a matter of resolving the IP for *outbound* requests, you'll need two things:

1. Somewhere *other* than at the website in question, where you'll be able to receive and analyse requests (e.g., by setting up a simple HTTP/S server at your local machine and enabling port forwarding to the port designated for that server to listen at, which is normally port 80; or, by having a secondary website set up elsewhere, with a different hosting company).
2. A script capable of sending outbound requests (CIDRAM is a more complex example, but writing a small PHP script for sending curl requests would probably be a little simpler for the sake of our purpose here).

Once you've got those two things, to get the IP address for outbound requests:

1. Host your script at the server in question, for which you want to get the IP address for outbound requests for.
2. Have your script send a request to a URL to the other location (your secondary website, or your new HTTP/S server which you set up or wherever). It doesn't matter whether or not the URL points to actual real, available resource, just as long as you've got access to the access logs for that other location.
3. Check the access logs for that other location and look for a record which corresponds to the request which your script sent.

Alternatively, you can firstly try updating, then checking the configuration page again to update `disabled_channels` to disable Macmathan's primary channel, in order to force CIDRAM to use the backup channel, to see whether that fixes everything (which may save some time at your end, if you'd prefer to not go through the aforementioned steps to get the IP address for outbound requests). ;-)

**Comment by mikeruss1** [comment] 2020-07-27 08:00
no change
I clicked to disable macmathan.info and its not sticking, reenter and its unclicked
deleted the channels in the cache, reentered and the cache is still showing macmathan.info
it also has his old bitbucket address, both have captcha errors

**Comment by mikeruss1** [comment] 2020-07-27 09:31
what I was thinking of with the outbound requests was whether you could change it to my actual IP address. I suspect the answer is no. I know what it is from the DNS, have tried to get it from php, and get the internal LAN address. Tried "$ip = exec('curl http://ipecho.net/plain; echo');" and I get the Control Panel IP address which is what CIDRAM is using.

My guess is even if we could get the DNS IP, routing probably wouldnt work?

**Comment by Maikuolan** [comment] 2020-07-30 07:18
> what I was thinking of with the outbound requests was whether you could change it to my actual IP address. I suspect the answer is no.

I mean.. I wouldn't call it impossible. Just thinking on it briefly, I imagine that it would, in *theory*, be possible to code something up in JavaScript to maybe fetch all the updates locally, through your own browser, and then maybe *upload* the updates from there, up to your installation, or to maybe dump the data associated with the update into a hidden form field and pass it onto your installation that way.. but those particular approaches would be a *lot* of work, and probably not the best ways to move forward, I think.

I've also seen *some*, certain shared hosting providers go into absolute fits of hysteria about what it is that we're doing, when we try doing it that way (I tried helping out an offline friend about a year back by installing CIDRAM on their personal website, a few of the front-end HTML assets didn't install properly, so I thought to try manually patching them in via the front-end file manager page.. only to end up getting my IP address listed as permanently banned at that hosting provider, within the first try, in less than 30 seconds of it, and with zero warnings whatsoever. Like.. seriously..? Over just HTML files, and with no warnings..? Good luck to anyone using *any* kind of content management systems at their servers, which happen to provide any kind of upload functionality or templating systems. I called up the hosting provider to ask them about it, and managed to get the IP address delisted within the hour.. but only after calling up a separate company, which apparently handled all their security stuff, because they wouldn't deal with it themselves. Needless to say, I didn't try that again, and stuck to just using combinations of FTP and cURL to help out said friend. *And yes, I could've just used a proxy or something to be able to continue working on the site, but I also wanted to better understand what was actually happening at the time, and to try to resolve that*). I mean.. I trust that most hosting providers aren't that overzealous (or, for those which are, would at least tell their users about their practices, or provide an option at cPanel or equivalent to enable/disable such things), but just something to keep in mind when contemplating the idea of building update mechanisms which work in those kinds of ways.

Aside from that though..? Not sure. What would *not* be possible, would be to have the update mechanism which CIDRAM already has, *without any modifications to it*, route through your actual IP address, instead of the IP address which it currently routes through.

We might need to think on it a bit more, to try to come up with other kind of solution, I guess. I had been preoccupied by some other things over the past few days, so haven't had much of a think on this particular problem yet myself (other than to the extent as already discussed here). I'll reply back again a little later when I have some more ideas (also feel free to reply again beforehand if you think of any yourself, or if the problem is otherwise somehow resolved before I get around to it).

**Comment by DanielRuf** [comment] 2020-07-30 07:32
Maybe use the proxy feature of curl (with curl_exec in PHP) and some public proxies. Just an idea but this should work in most cases.

**Comment by Maikuolan** [comment] 2020-07-30 07:49
> Maybe use the proxy feature of curl (with curl_exec in PHP) and some public proxies. Just an idea but this should work in most cases.

That sounds quite promising. I hadn't considered that before. I'll look more into that a little later today. Cheers. :-)

**Comment by mikeruss1** [comment] 2020-07-30 08:08
suggest dont get distracted by messing around with IP address. There seems to be the functionality built in to use macmathan's back up which isnt working ATM.

**Comment by 737simpilot** [comment] 2020-08-23 14:17
So why did Macmathan change sources yet again? It looks like he's hosting his own website again I thought he had to scrap his original website due to GDPR crap. If he's now got another website, GDPR could affect his data, no?

**Comment by DanielRuf** [comment] 2020-08-23 14:45
> GDPR could affect his data

Why should this be the case? Would be new to me.

**Comment by DanielRuf** [comment] 2020-08-23 14:46
> So why did Macmathan change sources yet again?

Best is to ask him directly.

**Comment by Maikuolan** [comment] 2020-09-20 04:58
Closing this, since it seems to basically be resolved now anyway. (Feel free to reply again if I've missed anything here and we can reopen this if needed. And yeah, probably best to just ask Macmathan directly about things like that). :-)

**Closed as completed by Maikuolan** 2020-09-20 04:58 UTC
Labels: Question, Resolved, Support
