### ISSUE TITLE
clearExpired() must be of the type array

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#148] opened 2019-10-23 03:40 UTC
```
Stack trace:
2019/10/23 08:44:25 [error] 32337#32337: *18187195 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Maikuolan\Common\Cache::clearExpired() must be of the type array, string given, called in /home/www/webapps/firewall/vault/functions.php on line 1519 and defined in /home/www/webapps/firewall/vault/classes/Maikuolan/Cache.php:511
  thrown in /home/www/webapps/firewall/vault/classes/Maikuolan/Cache.php on line 511" while reading response header from upstream, client: 66.102.8.111, server: example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/example.sock:", host: "www.example.com", 
#6 {main}
#5 /home/www/webapps/firewall/loader.php(93): require('/home/www/...')
#4 /home/www/webapps/firewall/vault/outgen.php(219): array_walk(Array, Object(Closure))
#3 [internal function]: {closure}('compat_bunnycdn...', 0)
#2 /home/www/webapps/firewall/vault/outgen.php(216): require('/home/www/...')
#1 /home/www/webapps/firewall/vault/compat_bunnycdn.php(20): {closure}('API')
#0 /home/www/webapps/firewall/vault/functions.php(1519): Maikuolan\Common\Cache->clearExpired('a:1:{s:8:"Bunny...')
```

Again all of my sites are down. God knows for how long. I've disabled bunnycdn compatibility for now to make my sites up and running.

This is the 3rd time this type of incident happened. Is it because I'm using v1 ? Should I upgrade to v2 ?

**Comment by Maikuolan** [comment] 2019-10-23 04:01
Investigating now. Will reply again shortly.

**Comment by Maikuolan** [comment] 2019-10-23 07:59
Latest commit adds an extra `is_array` guard to `InitialiseCacheSection` like as follows:

```PHP
    /** Fetch currently stored and clear expired entries. */
    if ($CIDRAM[$SectionName] = $CIDRAM['Cache']->getEntry($SectionName)) {
        if (is_array($CIDRAM[$SectionName]) && $CIDRAM['Cache']->clearExpired($CIDRAM[$SectionName])) {
            $CIDRAM[$SectionName . '-Modified'] = true;
        }
    }
```

That should theoretically prevent that kind of error message from appearing again. However, I haven't quite figured out yet how `clearExpired` ended up being supplied a string instead of an array in the first place, as following it up the chain to where its supplied data is generated in the first place, it should've already been an array anyway. I haven't been able to replicate the same behaviour at my end yet either.

Could be some kind of edge-case bug that I haven't noticed yet. I'll need to look into this further, I think. I'll reply again when I get a little further with this.

**Comment by Maikuolan** [comment] 2019-10-23 08:04
The..

```
Maikuolan\Common\Cache->clearExpired('a:1:{s:8:"Bunny...')
```

..part, in the stack trace, suggests that the cache entry isn't being unserialized properly after being fetched (thus causing it to be a string, per its serialized form, rather than an array, per its unserialized form, so, possibly something wrong with `unserializeEntry`). Anyway, looking into it at the moment.

**Comment by harryqt** [comment] 2019-10-23 08:32
Here's what I did:

Updated to latest commit (`1.15.1-DEV+19295312`) then enabled BunnyCDN compatibility layer **again**. No errors this time.

But I wasn't sure if bunncdn properly whitelisted so I copied all the IPs from the [edge server list](https://bunnycdn.com/api/system/edgeserverlist). Then tested those IPs using `IP Tester` with the `Also test against modules` **ticked**.

The result shows all of the ips are whitelisted except one:

`154.127.57.35 == Yes – Cloud service ("D.E.Tech", L14530:F0, [MU]), Cloud service ("NetStack Ltd", L18024:F0, [MU]), BunnyCDN bypass`

**Screenshot:**

![](https://s.put.re/PDH222do.png)

**Update**: I manually flushed the cache of bunnycdn, but the IP is still blocked. 🤨

**Comment by Maikuolan** [comment] 2019-10-23 13:05
Thanks for letting me know about that. Had some duplication in the signature files interfering with it. Latest signatures update, pushed as of a few minutes ago, should resolve that exception. :-)

**Comment by harryqt** [comment] 2019-10-27 00:02
> Had some duplication in the signature files interfering with it.

Can you elaborate a little? (just a little)

**Comment by Maikuolan** [comment] 2019-11-02 14:44
> Can you elaborate a little? (just a little)

Sorry for the delay. Got caught up doing other things and forgot about this.

Basically what I mean is that there were some different signatures across different signature sections which all blocked the same thing (this isn't generally desirable, but can sometimes happen, e.g., when we're blocking two different networks, and those two different networks have some interlacing, or both announce the same CIDRs, or when we have different signature sections, which exist for different reasons, but end up overlapping slightly with the things that they block). Anyway, that problem has been sorted out now, insofar as that particular IP address is concerned.

Anyway, keeping this issue open for now, because, although the problem shouldn't occur again due to the newly added guard code, I haven't quite figured out yet how exactly non-array data got parsed as one of `clearExpired`'s parameters. As long as everything seems to be working properly, and the problem isn't occurring anymore, I don't consider it particular urgent, but I'll get around to it when I can.

**Comment by Maikuolan** [comment] 2019-12-25 11:19
> I haven't quite figured out yet how exactly non-array data got parsed as one of `clearExpired`'s parameters.

Well.. I've managed to replicate the problem as per first encountered, and have figured out how it happened in the first place (i.e., wrong type of data being supplied). I was concerned that it might've been an indication of something more serious going on with the cache class itself, but yeah.. we're good. Just a minor case of oversight in the implementation of it. In short: Any implementation of said class anywhere, whether here or elsewhere, should firstly confirm whether data is actually an array before trying to run it through `clearExpired`; there are cases where said data mightn't be an array, intentionally and per design, and parsing such data will cause such errors to appear. Anyway, seeing as said oversight has been fixed since my previous reply here, I'll just go ahead and mark this issue as fixed and close it. :+1:

**Closed as completed** 2019-12-25 11:19 UTC
Labels: Bug, False Positive, Fixed
