### ISSUE TITLE
Aux Rules Editor

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#532] opened 2023-11-19 11:48 UTC
I added a User Agent

wp_is_mobile in a regex and then escaped it

wp\_is\_mobile

and then, after saving, the underscores were gone and became spaces?

**Comment by Maikuolan** [comment] 2023-11-21 14:55
Confirmed. The problem seems to be due to the way the YAML handler escapes and unescapes backslashes and non-breaking spaces. Investigating possible solutions now.

**Comment by Maikuolan** [comment] 2023-11-22 06:05
Should be fixed now. :-)

**Closed as completed** 2023-11-22 09:19 UTC
Labels: Bug, Fixed
