### ISSUE TITLE
logging standard_log is empty !

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#556] opened 2024-01-02 15:04 UTC
Hi,
My settings are

{mm}-{yyyy}.log

but from what i see it is always empty (from new year and after). I tried deleting it, recreated but empty. Tried also an other format with days, still zero.

![2024-01-02 17_07_11 - FileZilla](https://github.com/CIDRAM/CIDRAM/assets/4467158/5c742ebc-48a4-4eb6-8407-eec1ac1d8581)

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/604534a3-a696-4fc4-b573-1f789900e0ea)

Any ideas?

**Comment by Maikuolan** [comment] 2024-01-03 05:52
Offhandedly, no idea. :-/

I'll do some investigating and try to figure out some possibilities.

**Comment by eurobank** [comment] 2024-01-03 10:40
I tried to change caching, pdo, flat files, no luck.
I zeroed everything, caching, stats, tracking, no luck

I deleted the 01-2024.log and seems to be recreated but still empty. No errors anywhere.

Could that be a PHP version issue? I use 8.2.x latest. It is not easy to change PHP versions, still i could try that if needed....

**Comment by eurobank** [comment] 2024-01-03 11:54
Without touching anything, the log today started to populate (a few hours ago) !!!!!!!!!

I will check to see if it is completely logging thing and update here.

**Comment by Maikuolan** [comment] 2024-01-03 12:31
Maybe some kind of server-level file caching mechanism interfering with file changes?

**Comment by eurobank** [comment] 2024-01-03 12:44
@Maikuolan I have no idea, everything else was/is working fine on the server. Could be a server issue, of cource, also it could be the damn Imunify360 playing games, i dunno.

Maybe it is just magic and miracles :)

**Comment by eurobank** [comment] 2024-01-03 16:07
I'm closing this, still i'm puzzled why someking of error didn't appear.

**Comment by Maikuolan** [comment] 2024-01-03 17:09
Yeah.. I'm puzzled by this, too. :-/

I guess, if the problem has disappeared by itself, we could assume that perhaps the hosting provider had briefly changed something at the server (merely an assumption and no particular evidence for this, but lacking any other ideas, as good as any other assumption for now), realised the change was problematic (maybe another customer encountered some similar problem and reported it to them), and then reverted the changes accordingly, thus having everything work properly again, as was the case before the change. No idea though.

Although a good thing that the problem isn't occurring anymore, also difficult to do any further diagnosis or testing with that being the case.

If the problem reappears, feel free to reopen the issue and, assuming the problem remains in effect for long enough for us to do some further testing and diagnosis, maybe we'll be able to get a clearer idea about the cause. For now, marking as resolved.

**Comment by eurobank** [comment] 2024-01-05 15:15
Well as of today the log doesn't log anything more. Stopped at 1050 entries. For some hours doesn't log anything.

What must i do?

**Comment by eurobank** [comment] 2024-01-05 15:29
I opened a ticket with my hosting, and got this reply:

> Hello,
> 
> There is no mechanism that would stop you from writing data unless you've exceeded the amount of data your account can store. I show you as still having around ~15 GB of free space.
> 
> Thank you,

**Comment by eurobank** [comment] 2024-01-05 15:34
Imunify360 has a lot of things blocked from what i see:


Report black hash triggering | /home/cdr3/vault/events/default.php
-- | --



Started 3-4 days ago, so it IS related to Imunify360 and the hosting.

**Comment by Maikuolan** [comment] 2024-01-05 16:01
Not sure what hashes they're using (assuming that's what they mean by "report black hash triggering", but I'm not entirely sure whether that's the case), but [no other anti-virus scanners AFAICT](https://www.virustotal.com/gui/file/79d37a5cbdb1cff11ecccf0535d0e6b534bc3ee7578e4e2ad0c033c4696aa0c2/detection) are flagging the file, and none of its common hashes are turning up anything at Google, so.. I struggle to see an accidental hash collision between that file some other malicious file as being a remotely likely culprit (though labelling something as "report black hash triggering" does kind of sound like it could be alluding to that).

**Comment by eurobank** [comment] 2024-01-05 16:04
I can try to whitelist the file, to see if that solves the issue. But i prefered to let you know first.

**Comment by eurobank** [comment] 2024-01-05 16:07
@Maikuolan 

What do you understand from this: Why IPs are reported?

![2024-01-05 18_06_45-cPanel - — Mozilla Firefox](https://github.com/CIDRAM/CIDRAM/assets/4467158/7d833d43-d246-4bda-81e4-732fc3907ec4)

**Comment by Maikuolan** [comment] 2024-01-05 16:09
If they're relying on some kind of hash whitelist to detect bad files (i.e., flagging any files whose hashes don't match those on the hash whitelist), that could end up being a problem across the board, as any time I push any updates to CIDRAM and some files are changed, if their whitelist doesn't know about the new hashes for the changed files, they'll likely end up being flagged. The same would be true for any manually edited files, any time you change any files yourself (because again, they won't know about the new hashes for the changed files), any time logs are updated, etc.

I kind of hope they wouldn't consider relying on such a mechanism, because it's very normal for most websites everywhere to have some files which aren't standardised, aren't well-known to any hash lists, are customised to the websites in question, etc, because not all webmasters everywhere rely on standard CMS templates or blogs, and most webmasters will, of course, want to customise their websites according to their needs. Such a mechanism could end up being problematic for a lot of different people.

Any in case, if they provide a means for webmasters/customers to whitelist specific files or directories at their website, that should prevent the problem from occurring, I imagine, so might be the best way to go for now. Would still be good, ideally, to be able to get to the bottom of the problem, but if we don't, at least whitelisting should provide an avenue to solve it for now.

**Comment by Maikuolan** [comment] 2024-01-05 16:15
I assume "first script call from" would be referring to the IP address which initiates the requests where the file ends up being executed. Of course, because the file is a part of the CIDRAM core, and most CIDRAM core files tend to be always executed for any request which CIDRAM handles, and because most typical CIDRAM installations would execute for *every* request (assuming those requests are for a PHP file which CIDRAM is protecting), the "first script call from" in this case is likely to just reflect basically every request made to the website, good and bad requests alike.

**Comment by eurobank** [comment] 2024-01-05 16:18
Adding this specific issue and file to whitelist, made the log file to start again !!

But i see some errors/block to happen. 

i will keep an eye and come back ina few hours.

**Comment by Maikuolan** [comment] 2024-01-05 16:20
That all said.. If we can have Imunify360 stop flagging that file, logging *should*, I imagine, start working properly again. The reason: That file contains the event handlers for logging (an "event handler", in the context of CIDRAM, being some self-contained code which tells CIDRAM what to do when specific events occur, e.g., some data is gathered which needs to somehow be logged; CIDRAM will pass that data to the event handler, which then performs the logging). If Imunify360 is messing with that file, CIDRAM likely won't be able to access those event handlers, therefore not having anywhere to pass data onto when a log event occurs.

**Comment by Maikuolan** [comment] 2024-01-05 16:21
> Adding this specific issue and file to whitelist, made the log file to start again !!
> 
> But i see some errors/block to happen.
> 
> i will keep an eye and come back ina few hours.

Awesome; And sounds good. :+1:

**Comment by eurobank** [comment] 2024-01-05 19:53
After the white listing, all seem just fine.

**Closed as completed** 2024-01-05 22:55 UTC
Labels: Fixed, Compatibility, Resolved, Support
