### ISSUE TITLE
rate_limit allowance_period

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#345] opened 2022-10-21 14:04 UTC
Hello.

I'm unable to assign this to a MINUTE period of time. Maybe i shouldn't? or am i missing something?

I'm doing the same with Wordfence for Wordpress and works great for attacks. 10 hits per minute that is.

Thanks

**Comment by Maikuolan** [comment] 2022-10-21 15:28
Currently, to set it at exactly 10 minutes, you could specify something like `0.1667` for the number of hours, or to set it at exactly 1 minute, you could specify something like `0.0167` (a little more cumbersome than just simply writing "10 minutes" or "1 minute", but CIDRAM will still understand it correctly all the same).

Unfortunately though, at the moment, I haven't coded in a way to specify the preferred unit for time-based directives, and they all just accept either integer or float values (so all of them will just have some default unit they all prefer using to interpret the specified integer/float value).

Adding in support for that, from a technical perspective, would not be difficult. CIDRAM already has similar such support for volume-based directives (e.g., for the `max_bandwidth` directive, you can change the "KB" part of the value to an "MB", "GB", "TB", etc, and CIDRAM will interpret it correctly, though doubtful as it may be that anyone would ever possibly need such a large volume specified). The problem though, would be deciding on the exact best format to use for in the case of any such time-based directives.

Accepted international standards for representing an amount of time elapsed exist (e.g., `1°2′3″` for indicating "1 hour, 2 minutes, 3 seconds", but aside from those people which regularly use those standards, not everybody necessarily knows about them, they aren't always so easy to type on a standard US keyboard layout (and I don't want to force people to go fishing for the correct symbols), and there's the question of how to handle incorrectly formatted values, whether to accept, reject, etc. I could always just do `1:2:3` to avoid the keyboard issue, but then it looks like it's trying to specify an actual time of the day, rather than a duration, could be ambiguous/misleading, and we also don't know exactly whether something like `1:2` would mean "1 hour 2 minutes", "1 minute 2 seconds", "1 day 2 hours", or something else, so probably better to avoid using `1:2:3`. I don't want to write it as it would be spoken like "1 hour 2 minutes" either, because that would then lock the accepted format to English (or to whatever other language is used for in the case of accepting to write it as it would be spoken), or accepting a format like `1h2m3s` kind of has the same problem (if any CIDRAM user which doesn't know English sees that, they mightn't know whether "h" means "hour" or something else, or whether "m" means "minute", etc). I could, of course, just document it so that people would know, but even so, it still doesn't quite feel like the correct answer to me, either.

So, that all said.. I wasn't ever able to come to a decision regarding any potential best accepted format to support. '^.^

If we can decide on something, I might be able to add support for it, but until then, for the moment, just calculating an equivalent float value to use would be the best way to go, I think.

**Comment by Maikuolan** [comment] 2022-10-21 15:54
Though I suppose.. if I were to add support for something like `1°2′3″`, I could always just include some hints at the descriptions for the affected directives, too, and maybe change the default values for those directives to make use of the newly supported format, in order to make it more obvious for those unfamiliar with it..?

**Comment by eurobank** [comment] 2022-10-21 16:29
Thank you i will try all that. Is there any log when CIDRAM applies a rate limit?

Scrap this, I tried and works, with a log created. BUT since i control 5 sites with one instance of CIDRAM, all 5 sites were blocked. 

So the 10 per minute can't be used, i must come up with something greater. Like more minutes or more requests or both.

**Comment by mikeruss1** [comment] 2022-10-21 17:44
I think I suggested something on this a while ago. Needs to be more flexible, maybe the ability to incorporate a unit selector, say 5 events in 5 mins, or 2 events in 30 secs,

**Comment by Maikuolan** [comment] 2022-10-25 09:09
> BUT since i control 5 sites with one instance of CIDRAM, all 5 sites were blocked.

Do all 5 websites have the same domain name attached, or do they each have their own domain names?

I'm wondering whether it might be beneficial if I was to add an option to segregate the recorded rate limit data on the basis of domain name (meaning different domains could have different recorded rate limit data).

**Comment by eurobank** [comment] 2022-10-25 09:26
No totally different domains, same server, one instance of CIDRAM.

**Comment by eurobank** [comment] 2022-10-25 09:27
Also i have stopped to use the rate limit, because the Login of the sites stopped working for some reason. When trying to login we get some obscure warning and nothing else.

**Comment by Maikuolan** [comment] 2022-10-26 08:02
Working on something for this now.

**Comment by Maikuolan** [comment] 2022-10-29 16:30
Still working on the ability segregate the recorded rate limit data on the basis of domain name (nothing committed in that regard yet).

The configuration directives based on duration (e.g., `allowance_period`) have been reworked though. It should be much, much easier to specify exact durations now. Opted to just implement support for arctime notation, SI notation, and plain English all together. A bit simpler for the end-user that way. :-)

Haven't looked at the other stuff yet.

**Comment by Maikuolan** [comment] 2022-11-07 09:07
*Changelog excerpt (implemented at all current major versions):*
> - Added a new configuration directive, `segregate`, to specify whether the data for rate limiting should be segregated based on domain/hostname or shared.
> - Added a new page to the front-end for the purpose of viewing current rate limit quotas, useful for confirming whether rate limiting is working correctly at installations.

So, it should be possible to rate limit different websites easily via the same installation now, and also should be possible to confirm via the front-end whether it's working correctly or not.

A lot of the translations are still pending, but that often takes much more time to write than the actual code itself, so treating it as a lower priority for the moment (will get it sorted out at some point anyway).

The UI for the new page was created in a rush last night, so might look a little ugly at the moment. I'll try to tweak it a bit to make it look a little nicer a little later. AFAICT though, it seems to be working properly.

> Also i have stopped to use the rate limit, because the Login of the sites stopped working for some reason. When trying to login we get some obscure warning and nothing else.

When rate limiting is enabled, CIDRAM registers a procedure to PHP's shutdown routine (meaning, tells PHP to execute some specific piece of code specifically at the time when PHP finishes all other work necessary for the request at hand, before passing the output back to the server; in this case, necessary in order for CIDRAM to be able to capture how many bytes have been transferred for the request, to be able to judge bandwidth usage as part of its rate limiting feature). When rate limiting is disabled, CIDRAM doesn't touch PHP's shutdown routine at all, because the procedure in question isn't needed for anything else other than rate limiting.

I'm wondering whether that procedure might possibly be to blame for the login not working properly when rate limiting is enabled? I discovered, while working on the aforementioned changes, that the procedure could potentially generate warnings if CIDRAM's caching mechanism was shut down prematurely (i.e., if CIDRAM's own shutdown routine was triggered prior to PHP's shutdown routine being triggered), because the procedure was trying to trigger CIDRAM's own shutdown routine (which is needed in order to finalise any updates to the cache, rate limiting, etc, generated during the request at hand). To deal with that problem, I added a simple `isset()` check to the procedure to avoid triggering anything already triggered for the request at hand, thus avoiding any warnings being generated.

Possibly, that *might* resolve the problem with logins not working properly anymore when rate limiting is enabled. But, because I'm only speculating the cause, we would need to test it to confirm, I think (in case something else entirely is the cause).

**Comment by eurobank** [comment] 2022-11-07 10:33
I will have to try all that and update for the results.

**Comment by eurobank** [comment] 2022-11-12 13:18
The segragation seems to work fine.

Questions:

1. Is there a template when rate limiting is activated ? ( or a message?)
2. How long does the rate limiting lasts?
3. When rate limiting is activated, while the visitor sees an empty page, if you check the html code, the full page is there!

**Comment by Maikuolan** [comment] 2022-11-12 13:34
> The segragation seems to work fine.

Glad to hear it. :-)

> 1. Is there a template when rate limiting is activated ? ( or a message?)

Currently, it uses the same output template as the standard "access denied" page, and the message it displays is the standard "access denied" message, but I've been thinking the message should probably be changed to something else, to make it clearer to users what's going on (something on the to-do list).

If you want it to not use any output template though (i.e., send no page data at all), it can be turned on/off via the configuration:

![rltemplate](https://user-images.githubusercontent.com/12571108/201476043-12f25aff-cd64-4453-89a3-85ccfa9d8e5d.png)


> 2. How long does the rate limiting lasts?

Once rate limiting has been invoked, it'll last until the total number of records for the rate limited address/entity/etc no longer exceed the configured limits (so, as long as the rate limited address/entity/users/bot/etc doesn't continually hammer the website after being rate limited, thus continually incurring additional records and likely extending the time, the rate limiting should wear off within a period of time not exceeding the configured tracktime).

So, for example, if you configure it for a day, it'll usually last less than that amount of time, but potentially up to that entire amount of time if the rate limited entity was hammering the website right up until the point that rate limiting was invoked, or for longer than that if they don't stop even after being told that they've been rate limited.

![tt](https://user-images.githubusercontent.com/12571108/201476530-5fc363bc-ff84-4ce1-b47d-2b4295c78b3a.png)

> 3. When rate limiting is activated, while the visitor sees an empty page, if you check the html code, the full page is there!

Does the HTML code look like something generated by CIDRAM, or something generated by the website?

**Comment by eurobank** [comment] 2022-11-12 13:50
For now, in  my setup, when rete limited, an empty page is displayed.

And in the html source, you see the complete page, from the script. Same as the displayed. No caching involved (that script has no caching anywhere). 

In Wordpress when rate limited, there is NO html source of anything (empty).

**Comment by eurobank** [comment] 2022-11-12 13:51
Also about sagregation:

For tests, i have 10 hits PER MINUTE.

When one domain is rate limited, i try an other domain in just 3 refreshes it gets rate limited. (see below)

**Comment by eurobank** [comment] 2022-11-12 13:53
About the template, i just see an empty page:

![Screenshot](https://user-images.githubusercontent.com/4467158/201477282-92547d05-e936-4445-975e-8475386ffd0e.png)

**Comment by eurobank** [comment] 2022-11-12 13:56
This is a ghost house not a server :)

The 3 times rate limit happens only with Wordpress sites. Go figure....

**Comment by Maikuolan** [comment] 2022-11-12 14:01
> The 3 times rate limit happens only with Wordpress sites. Go figure....

I wonder whether each page load is invoking multiple requests..? I.e., the browser sends a request, a page is returned, and that page contains embedded frames, links to scripts, css, etc, located on the same server, all also being processed by PHP the same as the initial requested resource, all sitting behind CIDRAM, the browser then follows those embeds/links/etc sending subsequent requests to fetch those resources.. so when the user makes a single request, thinking it's just one request only, CIDRAM ends up seeing maybe ~2, ~3, or more requests instead due that embedding/linking.

Just speculating, but knowing how WordPress is structured, I reckon it's probably a safe bet that something like that is what's going on.

**Comment by Maikuolan** [comment] 2022-11-12 14:04
Even things like images, which PHP usually doesn't touch, seeing as PHP is only intended to deal with PHP files and PHP code: If they're being redirected as friendly URLs to a WordPress entrypoint in order to have WordPress pull images from its database, rather than just calling images directly from the server.. that would be extra requests there. :-/

**Comment by Maikuolan** [comment] 2022-11-12 14:06
> And in the html source, you see the complete page, from the script. Same as the displayed. No caching involved (that script has no caching anywhere).

Definitely odd. Offhandedly, not sure why that would be happening. I'll try to figure out whether I can replicate something similar though.

**Comment by eurobank** [comment] 2022-11-12 15:52
ok, to sum a bit.

The issue of html code only shows in NON Wordpresss sites.

The 4 refreshes only shows ON Wordpress sites. And it is not site specific, i tried it in 3 different WP sites, all the same. At the 4th refresh, bam. What i do for test, i stay at the Home page and refresh. I have even removed caching plugin for a while, nothing changed.

If you want to see it yourself, let me send you by email the links of 5 sites.

**Comment by Maikuolan** [comment] 2022-11-13 16:32
> If you want to see it yourself, let me send you by email the links of 5 sites.

Sounds like a plan. :+1: Do you have my email address?

**Comment by eurobank** [comment] 2022-11-13 18:45
nope. no email address.

**Comment by Maikuolan** [comment] 2022-11-15 15:11
Okay. You can email me at, my username here at GitHub, at gmail dot com. :-)

**Comment by eurobank** [comment] 2022-11-28 09:12
btw: I have emailed you 2 weeks ago and i even invited you on Skype. No reply.

**Closed as completed** 2023-03-17 16:50 UTC
Labels: Resolved, QA
