### ISSUE TITLE
CIDRAM update modules problem

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#213] opened 2021-04-15 17:15 UTC
I have 7 modules showing "please update manually" .. like this

Bad TLDs blocker moduleBlocks hosts belonging to TLDs frequently used by spammers, hackers, and other nefarious entities.Used with: signatures->modulesFalse positive risk: Low | 2021.89.309Total Size: 2.02 KBFilename: module_badtlds.php | 2021.95.583Total Size: 2.02 KB | Outdated (please update manually)!Component is active.DeactivateDeactivate + UninstallVerify
-- | -- | -- | --

odd thing they all have the same current version .. 2021.89.309 .. and none have an install option
using 1.18.1
tried repair all, no effect
???

**Comment by Maikuolan** [comment] 2021-04-16 02:14
Is it showing any updates available for CIDRAM itself? I actually recently removed the "please update manually" string from the language data entirely, so it shouldn't even be possible for that message to appear anymore as of the latest versions.

If there are updates available for CIDRAM itself, you may just need to update that first, and then the module updates should become available again (due to there being some needed changes recently made to CIDRAM). Otherwise though, if it isn't showing any updates available for CIDRAM, there might be something more going on.

**Comment by mikeruss1** [comment] 2021-04-16 07:19
update failed. Tried to verify ...
CIDRAM – Verification failed! Component could be corrupted.
I changed the flock timeout in cache.php - related?
the last time I updated CIDRAM was probably 3-4 weeks ago
the "please update manually" messages had all gone when I looked before trying the update. Only updates there were normal.

**Comment by Maikuolan** [comment] 2021-04-16 07:34
When verifying, if you click on the *"... – Verification failed! Component could be corrupted."* message, it'll display more detailed information about exactly which files caused the failure, like so:

![a](https://user-images.githubusercontent.com/12571108/114988427-e7878c00-9ec8-11eb-985d-eb587b2b39f8.png)
![b](https://user-images.githubusercontent.com/12571108/114988431-e8202280-9ec8-11eb-8e2c-17daaf39c624.png)

I already assume that `classes/Maikuolan/Cache.php` will be one of the files, due to the flock change, so no worries about that one, but if you check those details, are there any other files in there failing?

Cheers.

**Comment by mikeruss1** [comment] 2021-04-16 07:40
no just cache.php
classes/Maikuolan/Cache.php – Integrity check: Failed – Sanity check: Passed
Actual – 0614ec058e7b00387e15b89724604696a9eaae9f820dd9ed813f0c6a9ced2385:26092
Expected – cf3a1cc01491ee8ae30594685d652e85b24d7f333fc48510fd77f08d1a93643c:26092
do I change it back
there were a bunch in fe_assets it skipped

**Comment by mikeruss1** [comment] 2021-04-16 13:35
um ...changed cache.php back and no verification issue. However still wont update
CIDRAM – Failed to update! +0 bytes | -0 bytes | 15.303
the 7 modules are showing as needing updating, but "please update manually" has gone, though nothing has changed. None of them have an update option and they are all showing current version as 2021.89.309

**Comment by Maikuolan** [comment] 2021-04-16 14:10
> CIDRAM – Failed to update! +0 bytes | -0 bytes | 15.303

15 seconds is quite a long time to try to update, so I'm guessing, it's probably something happening with one of the later files in the update.

I'll do some more testing at my end and reply back here soon.

**Comment by Maikuolan** [comment] 2021-04-16 14:33
I downloaded the ZIP release for CIDRAM v1.18.0 just now, installed it at my local machine, went to the front-end updates page, attempted to update to the latest available v1 version.. No problem encountered.

![Untitled](https://user-images.githubusercontent.com/12571108/115038087-c727f380-9f01-11eb-93c1-bc4a27866c95.png)

So, at the very least, it seems that I haven't accidentally committed any wrong files, and that there hasn't been any bad metadata snuck into the updates (otherwise, if such was the case, nobody would be able to update, myself included).

Though, that said, the attempt took even longer at my end than it did at yours (almost 28 seconds! 29, if we include the L10N data automatically updated alongside it at the same time), which is slightly concerning, in the sense of possible timeouts occurring for some users (since many webservers have a default timeout at 30 seconds), potentially causing faulty updates to occur, or updates being half finished and the process forcibly aborted by webservers before the updater even has a chance to revert any failed updates. Still.. Yours showed 15 seconds, which is less than half that, so.. I'm guessing, not the case here, either.

Since nothing else failed to verify at your end, I'm guessing the problem isn't corrupted files, nor anything external tampering with CIDRAM's internal files. I wouldn't worry too much about skipped files; If verification skips something, it just means that it either doesn't have any expected hashes available to check the files against, or that I haven't coded in any sanity checks for the particular type of file in question (depending on which was skipped, integrity or sanity check).

We'll need to figure out firstly why CIDRAM itself is failing to update. The modules definitely won't be able to update properly until CIDRAM is able to be updated to the latest version. So, I'm focusing on figuring that out first, at least, for now. Once that's sorted out, if the modules still fail to update, then I guess, that would mean that something else is going on too, but I'm pretty sure you'll be able to easily and safely update the modules once again once that's sorted out.

I wonder whether it might be permissions, maybe..? Maybe permissions changed on something somewhere..? Did you manually upload (or reupload) anything to the CIDRAM vault recently, or manually edit anything in there recently (i.e., not from the front-end, but by, e.g., downloading, editing in a text editor, and then FTP'ing it back to the vault)? I know there's the `Cache.php` file, but since there haven't been any changes to that file between your currently used version and the latest, I doubt that would be the culprit. If there aren't any other possible candidates though, it might be worth checking the write permissions on the file anyway, just to be safe. If there are others, I would check those, just to be safe, too.

Haven't thought of any other possibilities yet, but still testing and investigating at my end, to see whether I can come up with anything else.

**Comment by mikeruss1** [comment] 2021-04-16 17:30
OK you are going to love this ....
went back in to the front end, updated to 1.18.2 successfully, no problem, and all the modules updated fine, and I get the new format for the updates list, satisfied etc. I havent changed anything to get this to work.
log out, go back in, and its showing the old version, 1.18.1, and modules need updating
repeat update etc etc .. same thing
look in the vault and the update has been done, latest files showing todays date/time.
so my conclusion, its updated fine, but is somehow showing old version info???????
good luck !!!

**Comment by mikeruss1** [comment] 2021-04-16 21:49
its got a mind of its own - logged on again and I have 1.18.2 in the updates page
front page says 1.18.1
System information:
CIDRAM version used: 1.18.1
PHP version used: 7.4.16
Extension➡Installed/Available

**Comment by Maikuolan** [comment] 2021-04-17 00:32
Hm.. No idea about that. Server caching, maybe..?

**Comment by mikeruss1** [comment] 2021-04-17 06:19
its got to be something like cache, weird, never seen an effect as bad as that. I have had delays of a few seconds in FTP updates of php files showing in a browser, but nothing as gross as this.
sorry to take up your time.

**Comment by mikeruss1** [comment] 2021-04-17 08:23
just had a thought - whats the file extension of the file that controls version info - .dat?
I have this in .htaccess
ExpiresByType text/html "access 2 hours"

Ah ... I see it looks like the frontend uses html files - have removed it
I suspect thats the problem?

**Comment by Maikuolan** [comment] 2021-04-17 12:01
> just had a thought - whats the file extension of the file that controls version info - .dat?

Yep. :-)

> I have this in .htaccess
> ExpiresByType text/html "access 2 hours"
> 
> Ah ... I see it looks like the frontend uses html files - have removed it
> I suspect thats the problem?

It possibly could be that. Might need to experiment to confirm though.

**Comment by mikeruss1** [comment] 2021-04-17 12:16
I wouldnt put time into it, I can see there was a big change in the layout. Fits the symptoms too.

**Comment by Maikuolan** [comment] 2021-04-17 13:23
Cool cool. Mark this as resolved now..? What do you reckon?

**Comment by mikeruss1** [comment] 2021-04-17 14:02
Yes, thank you.

**Closed as completed** 2021-04-17 14:26 UTC
Labels: Resolved, Support
